var grQuests = {
    "ch6": [
        "Train 20 Sorceresses::Y",
        "Research Dwarven Portal Site::N",
        "Build Dwarven Portal Site::N",
        "Produce Beverages 1 time::N",
        "Produce Bread 10 times::N",
        "Research City Expansion 21::N",
        "Gain 1000 Steel::N",
        "Produce 10 Simple Tools::N",
        "Research Portal Tracks::N",
        "Gain 50,000 Coins::N",
        "Research Granite Mine::N",
        "Place 1 Granite Mine::N",
        "Have at least 1 piece of Portal Tracks::N",
        "Gain 100 Granite::N",
        "Research Dwarven Style Marble Manufactory::N",
        "Research Dwarven Style Planks Manufactory::N",
        "Research Dwarven Steel Manufactory::N",
        "Have a Marble Manufactory at level 16 or higher::N", //boosted
        //"Have a Planks Manufactory at level 16 or higher",
        //"Have a Steel Manufactory at level 16 or higher",
        "Research Copper Foundry::N",
        "Produce Copper Coins 10 times::N",
        "Produce 1 Dwarven Statue::N",
        "Produce Beverages 100 times::N",
        "Research Ancient Grounds::N",
        "Build Ancient Grounds::N",
        "Gain 5000 Supplies::N",
        "Gain 100,000 Coins::N",
        "Research Dwarven Style Main Hall::N",
        "Research Dwarven Style Street::N",
        "Build Dwarven Street::N",
        "Research Tavern and Temple::N",
        "Build Wayfarer's Tavern::N",
        "Have the Dwarven Portal Site at Level 2 or higher::Y",
        "Research Dwarven Style Residential Buildings::Y",
        "Have 1 Residence at level 16 or higher::N",  //not sure about mandatory
        "Research Dwarven Style Workshop::N", // not sure
        "Have 1 Workshop at level 16 or higher::N", //-
        "Research Dwarven Style Barracks::Y",
        "Have 2 Workshops at level 16 or higher::N", //-
        "Produce 5 Advanced Tools::Y",
        "Gain 1000 Steel::Y",
        "Gain 1000 Planks::Y",
        "Research 'Sword Acrobat'::Y",
        "Train 100 Sword Acrobats::Y",
        "Fight and win in 5 Encounters::Y",
        "Have 2 Residences at level 16 or higher::N",  //-
        "Research Squad Size Upgrade 17::Y",
        "Research Dwarven Style Armory::Y",
        "Gain 500 Granite::Y",
        "Research 'Granite Golem'::Y",
        "Train 30 Granite Golems::Y",
        "Produce 30 Beverages::Y",
        "Produce 3 Toolboxes::Y",
        "Gain 500 Granite::Y",
        "Produce 25 Simple Tools + Produce 25 Beverages::Y",
        "Produce Copper Buckles 10 times::Y",
        "Gain 150,000 Coins::Y",
        "Produce 3 Baskets of Groceries + Produce 30 Beverages::Y",
        "Train 500 Units::Y",
        "Gain 4000 Goods::Y",
        "Place 5 Trade Offers::Y",
        "Accept 6 Trade Offers::Y",
        "Build 3 culture buildings::Y",
        "Gain 100 Culture::Y",
        "Gain 100 Population::Y",
        "Train 150 Sorceresses::Y",
        "Train 300 Units::Y",
        "Gain 2500 Goods::Y",
    ],
    "ch7": [
        "Research Advanced Scouts::N",
        "Sell your Dwarven Portal Site::Y",
        "Train 30 Sorceresses::N",
        "Research Fairy Portal Site::N",
        "Have the Fairy Portal Site::N",
        "Gain 200 Elixir::N",
        "Produce Beverages 10 times::N",
        "Produce Bread 10 times::N",
        "Produce Simple Tools 10 times::N",
        "Spend 20 knowledge Points::N",
        "Produce Basket of Groceries 10 times::N",
        "Research Flower Lane::N",
        "Have at least 1 Flower Lane:N",
        "Research Trees and lampions::N",
        "Have Culture Bonus of 125% maximum::Y",
        "Have at least 1 Cocoon Lampions building::N",
        "Produce Beverages 1 times::N",
        "Gain 1 Scroll::N",
        "Gain 1 Magic Dust::N",
        "Research Day Farm::N",
        "Gain 100K coins::N",
        "Have at Least 1 Day Farm::N",
        "Produce Sunflowers 5 times::N",
        "Produce Velvet 3 times::N",
        "Have the Fairy Portal at Level 2 or higher::N",
        "Produce Sunflowers 10 times::N",
        "Have at least 2 Day Farms::N",
        "Research Night Farm::N",
        "Have 1 Night Farm::N",
        "Gain 2000 Crystal::N",
        "Produce Nightshade 10 times::N",
        "Have the Fairy Portal at Level 3 or higher::N",
        "Research Fairy Style Residence::N",
        "Have 1 Residence at Level 18 or Higher::N",
        "Have 1 Day Farm at Level 3 or Higher::N",
        "Have 1 night Farm at Level 3 or Higher::N",
        "Have 2 Residences at Level 18 or Higher::N",
        "Produce Cocoons 15 times::N",
        "Produce Dream Sheep 15 times::N",
        "Research Fairy Style Main Hall::N",
        "Produce Ambrosia 5 times::Y",
        "Produce Night Essence 5 times::Y",
        "Research Blossom Street::N",
        "Produce Nightshade 20 times::N",
        "Have the Fairy Portal Site at Level 4::N",
        "Research Fairy Style Crystal Manufactories::N",
        "Research Fairy Style Scrolls Manufactories::N",
        "Research Fairy Silk Manufactories::N",
        "Have a Tier 2 Boosted Manufactory at level 16 or higher::N",
        "Research Pond of Recreation::N",
        "Have at least 1 Pond of Recreation::N",
        "Research City Expansion 31::N",
        "Research Fairies Ancient Wonders::N", //diamonds
        "Research Merceenary Camp Blossom Mage::Y",
        "Have a Mercenary Camp::Y",
        "Train 40 Blossom Mage::Y",
        "Research Fairy Style Workshops::Y",
        "Have a workshop Level 18 or higher::Y",
        "Research Squad Size Upgrade 22::Y",
        "Produce Sunflowers 10 times::Y",
        "Produce Cocoons 7 times::Y",
        "Produce Velvet 15 times::Y",
        "Research Drone Rider::Y",
        "Gain 10,000 Supplies::Y",
        "Train 30 Drone Riders::Y",
        "Research Fairy Style Barracks::Y",
        "Have a Barracks at level 18 or higher::Y",
        "Research Shrine and Lantern::Y",
        "Have 1 Small Shrine::Y",
        "Train 500 Units::Y",
        "Gain 4000 Goods::Y",
        "Place 5 trade Offeres::Y",
        "Build 3 Cultural Buildings::Y",
        "Gain 100 Culture::Y",
        "Gain 100 Population::Y",
        "Train 150 Sorceresses::Y",
    ],
    "ch8": [
        "",
    ],
}