var grQuests = {
    "ch6": [
        "Train 20 Sorceresses",
        "Research Dwarven Portal Site",
        "Build Dwarven Portal Site",
        "Produce Beverages 1 time",
        "Produce Bread 10 times",
        "Research City Expansion 21",
        "Gain 1000 Steel",
        "Produce 10 Simple Tools",
        "Research Portal Tracks",
        "Gain 50,000 Coins",
        "Research Granite Mine",
        "Place 1 Granite Mine",
        "Have at least 1 piece of Portal Tracks",
        "Gain 100 Granite",
        "Research Dwarven Style Marble Manufactory",
        "Research Dwarven Style Planks Manufactory",
        "Research Dwarven Steel Manufactory",
        "Have a Marble Manufactory at level 16 or higher",
        "Have a Planks Manufactory at level 16 or higher",
        "Have a Steel Manufactory at level 16 or higher",
        "Research Copper Foundry",
        "Produce Copper Coins 10 times",
        "Produce 1 Dwarven Statue",
        "Produce Beverages 100 times",
        "Research Ancient Grounds",
        "Build Ancient Grounds",
        "Gain 5000 Supplies",
        "Gain 100,000 Coins",
        "Research Dwarven Style Main Hall",
        "Research Dwarven Style Street",
        "Build Dwarven Street",
        "Research Tavern and Temple",
        "Build Wayfarer's Tavern",
        "Have the Dwarven Portal Site at Level 2 or higher",
        "Research Dwarven Style Residential Buildings",
        "Have 1 Residence at level 16 or higher",
        "Research Dwarven Style Workshop",
        "Have 1 Workshop at level 16 or higher", //8530
        "Research Dwarven Style Barracks",
        "Have 2 Workshops at level 16 or higher",
        "Produce 5 Advanced Tools",
        "Gain 1000 Steel",
        "Gain 1000 Planks",
        "Research 'Sword Acrobat'",
        "Train 100 Sword Acrobats",
        "Fight and win in 5 Encounters",
        "Have 2 Residences at level 16 or higher",
        "Research Squad Size Upgrade 17",
        "Research Dwarven Style Armory",
        "Gain 500 Granite",
        "Research 'Granite Golem'",
        "Train 30 Granite Golems",
        "Produce 30 Beverages",
        "Produce 3 Toolboxes",
        "Gain 500 Granite",
        "Produce 25 Simple Tools AND produce 25 Beverages",
        "Produce Copper Buckles 10 times",
        "Gain 150,000 Coins",
        "Produce 3 Baskets of Groceries AND produce 30 Beverages",
        "Fight and win in 3 Encounters",
        "Gain 4000 Marble",
        "Gain 4000 Steel",
        "Gain 4000 Planks",//9070
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    "ch7": [
        "Získaj 1x ľubovoľné kúzlo"
    ],
}