var dailyPrizes = {
    
    "july_xxi_": [
        "A_Evt_July_XXI_Leviathan_Ferry",
        "A_Evt_MM_XIX_MantaRay",
        "A_Evt_MM_XIX_Seahorse"
    ],

    "july_xxi_": [

    ],

    "june_xxi_": [
        "A_Evt_June_XXI_Unexpected_Morning",
        "A_Evt_July_XX_Golem_Cave",
        "INS_RF_GRR_10",
        "A_Evt_June_XXI_Body_Transmutation",
        "A_Evt_July_XX_Hedge_Beard_Treant",
        "A_Evt_July_XX_Wizard_Spell_Shop",
        "INS_UNIT_TG_LR_10",
        "A_Evt_June_XXI_Hungry_Treasure",
        "A_Evt_July_XX_Hedge_Beard_Treant",
        "A_Evt_June_XXI_Active_Fissure",
        "A_Evt_July_XX_Astral_Crevice",
        "INS_UNIT_TG_HM_10",
        "A_Evt_June_XXI_Hungry_Treasure",
        "A_Evt_July_XX_Golem_Cave",
        "A_Evt_June_XXI_Unexpected_Morning",
        "INS_KP_AW_10",
        "A_Evt_June_XXI_Active_Fissure",
        "A_Evt_July_XX_Copper_Dragon",
        "INS_UNIT_TG_HR_10",
        "A_Evt_July_XX_Mana_Crystal_Merchant",
        "INS_KP_AW_10",
        "A_Evt_June_XXI_Body_Transmutation"
    ],

    "may_xxi_": [
        "A_Evt_May_XXI_Bumblebee_Stables",
        "A_Evt_May_XXI_Blossom_Light_post",
        "INS_RF_GRR_10",
        "A_Evt_May_XX_Public_Stage",
        "INS_UNIT_TG_HR_10",
        "A_Evt_May_XXI_Faerie_Sand_Garden",
        "INS_KP_AW_10",
        "A_Evt_May_XXI_Dragonfly_Pond",
        "A_Evt_May_XXI_Petal_Bridge",
        "INS_UNIT_MC_LR_10",
        "A_Evt_May_XXI_Faerie_Inn",
        "A_Evt_May_XX_Halfling_Stage",
        "A_Evt_May_XX_Cake_Counter",
        "A_Evt_May_XX_Cotton_Candy_Magic",
        "A_Evt_May_XXI_Bumblebee_Stables",
        "A_Evt_May_XXI_Petal_Bridge",
        "INS_UNIT_MC_LM_10",
        "INS_KP_AW_10",
        "A_Evt_May_XXI_Faerie_Inn",
        "INS_UNIT_TG_MA_10",
        "A_Evt_May_XXI_Faerie_Sand_Garden",
        "A_Evt_May_XXI_Blossom_Light_post"
    ],

    "march_xxi_": [
        "A_Evt_Easter_XX_Phoenix_Lava",
        "A_Evt_March_XXI_Phoenix_Chick",
        "INS_RF_GRR_10",
        "A_Evt_March_XXI_Eggshell_Pavillon",
        "INS_UNIT_LM_15",
        "A_Evt_Easter_XX_Phoenix_Anatomy",
        "INS_KP_AW_10",
        "A_Evt_March_XXI_Temple_of_Embers",
        "A_Evt_March_XXI_Phoenix_Water_Mill",
        "A_Evt_March_XXI_Phoenix_Rider",
        "A_Evt_March_XXI_Eggshell_Shrine",
        "A_Evt_Easter_Vii_BurningEgg",
        "INS_UNIT_MC_LR_10",
        "A_Evt_Golden_Palace",
        "A_Evt_March_XXI_Phoenix_Chick",
        "A_Evt_March_XXI_Eggshell_Pavillon",
        "A_Evt_March_XXI_Phoenix_Water_Mill",
        "INS_UNIT_MC_LM_10",
        "A_Evt_March_XXI_Eggshell_Shrine",
        "INS_KP_AW_10",
        "A_Evt_March_XXI_Phoenix_Rider",
        "A_Evt_March_XXI_Temple_of_Embers"
    ],

    "february_xxi_": [
        "A_Evt_February_XXI_Elder_Snowman",
        "A_Evt_February_XXI_Yeti_Hot_Spring",
        "INS_RF_GRR_10",
        "A_Evt_Car_XIX_Elven_Wagon",
        "A_Evt_Car_XX_Deers_Golems",
        "A_Evt_Val_Balcony",
        "A_Evt_Car_XX_Halfling_Wagon",
        "A_Evt_February_XXI_Aureate_Willow",
        "A_Evt_Car_XIX_Dancing_People",
        "A_Evt_February_XXI_Dawn_Of_Spring_Shrine",
        "A_Evt_Car_XIX_Beauty_Puppet",
        "A_Evt_Car_XX_Dragon_Puppet",
        "INS_UNIT_LR_10",
        "A_Evt_Car_XIX_Orc_Wagon",
        "A_Evt_February_XXI_Sun_Loop",
        "INS_KP_AW_10",
        "A_Evt_February_XXI_Elder_Snowman",
        "A_Evt_Car_XX_Bubble_Mask",
        "A_Evt_Car_XX_Constructs_Wagon",
        "INS_UNIT_LM_10",
        "A_Evt_Car_XX_Dwarven_Wagon",
        "A_Evt_February_XXI_Lifeblood_Cone"
    ]
}
