var dailyPrizes = {
    
    "autumn_xxii_": [
        "A_Evt_September_XXI_Calligraphy_Class",
        "A_Evt_Autumn_XXII_Succulent_Crabs",
        "INS_UNIT_MC_LM_10",
        "A_Evt_Autumn_XVIII_Tomato_Jury",
        "kp_{15}",
        "A_Evt_Autumn_XXII_The_Flying_Chopsticks",
        "runeshards-1_{2}",
        "A_Evt_Prod_Nutcracker",
        "INS_UNIT_MC_MA_10",
        "A_Evt_September_XXI_Training_Dojo",
        "INS_KP_AW_10{2}",
        "A_Evt_Autumn_XXII_Luscious_Cakes",
        "INS_REV_SQD_50",
        "INS_UNIT_MC_LR_10",
        "A_Evt_Autumn_XVIII_Green_Pond",
        "INS_RF_GRR_5",
        "A_Evt_Autumn_XXII_Succulent_Crabs",
        "A_Evt_Prod_NutStub",
        "kp_{10}",
        "A_Evt_Autumn_XXII_The_Flying_Chopsticks",
        "INS_UNIT_MC_HM_10",
        "A_Evt_Autumn_XXII_Luscious_Cakes",
    ],
    
    "august_xxii_": [
        "A_Evt_August_XXII_Lunar_Factory",
        "A_Evt_August_XXII_Solar_Training_Grounds",
        "INS_UNIT_MC_MA_10",
        "A_Evt_August_XXII_Warriors_Gate",
        "runeshards-1_{2}",
        "A_Evt_February_XXI_Sun_Loop",
        "kp_{15}",
        "A_Evt_Summer_XVIII_Mystical_Lace",
        "INS_REV_SQD_50",
        "A_Evt_Car_XX_Dwarven_Wagon",
        "INS_KP_AW_20",
        "A_Evt_Astronomi_XVIII_StoneOfTheStars",
        "INS_RF_GRR_5",
        "INS_UNIT_TG_HR_10",
        "A_Evt_May_XX_Food_Market",
        "INS_REV_SQD_25{2}",
        "A_Evt_August_XXII_Lunar_Factory",
        "A_Evt_August_XXII_Warriors_Gate",
        "INS_UNIT_MC_LR_10",
        "A_Evt_Summer_XVIII_Monopteros",
        "kp_{10}",
        "A_Evt_August_XXII_Solar_Training_Grounds",
    ],

    "july_xxii_": [
        "A_Evt_MM_XIX_MantaRay",
        "A_Evt_MM_XIX_SharkTower",
        "goods_standard_sentient_{1}", //frog_default3
        "A_Evt_July_XXI_Leviathan_Ferry",
        "kp_{10}",
        "A_Evt_July_XXI_Diving_Platform",
        "INS_UNIT_TG_HM_10",
        "A_Evt_July_XXI_Manta_Boat",
        "INS_REV_SQD_25",
        "A_Evt_July_XXII_Coral_Fountain",
        "runeshards-1_{2}",  //frog_runeshards2
        "A_Evt_July_XXI_Mechanical_Seahorse",
        "INS_RF_GRR_10",  //frog_grr_10
        "INS_UNIT_TG_HR_10",
        "A_Evt_July_XXII_Azure_Stables",
        "INS_KP_AW_20",
        "A_Evt_MM_XIX_WaterBubble",
        "goods_standard_sentient_{1}",  //frog_default2
        "A_Evt_MM_XIX_Corals",
        "A_Evt_MM_XIX_Seahorse",
        "runeshards-1_{3}",  //frog_runeshards1
        "A_Evt_MM_XIX_CrabHotel",
    ],
    
    "may_xxii_": [
        "A_Evt_May_XXII_Tender_Tag_Team",
        "A_Evt_May_XXI_Bumblebee_Stables",
        "goods_standard_sentient_{1}",  //A pack of standard or sentient goods (depending on chapter)
        "A_Evt_May_XXI_Blossom_Light_post",
        "INS_UNIT_MA_10",
        "A_Evt_May_XXII_Primordial_Gecko",
        "kp_{15}",
        "A_Evt_May_XX_Halfling_Stage",
        "runeshards-1_{4}",
        "A_Evt_May_XXII_Soothing_Pond",
        "INS_KP_AW_20",
        "INS_RF_GRR_5{2}",
        "A_Evt_May_XXI_Petal_Bridge",
        "INS_UNIT_TG_HR_10",
        "A_Evt_May_XXII_Tender_Tag_Team",
        "goods_standard_sentient_{1}",  //10x frog_sentient_q_3_plus_1
        "A_Evt_May_XXII_Primordial_Gecko",
        "goods_standard_sentient_{1}",
        "INS_KP_AW_30",
        "A_Evt_February_XXI_Aureate_Willow",
        "kp_{15}",
        "A_Evt_May_XXII_Soothing_Pond",
    ],
    
    "easter_xxii_": [
        "A_Evt_Phoenix_Lake",
        "A_Evt_Easter_XXII_Voice_of_the_Prophet",
        "INS_UNIT_TG_LM_10",
        "A_Evt_Easter_XXII_Rod_of_Ascleptius",
        "A_Evt_Easter_XX_Phoenix_Lava",
        "kp_{15}",
        "INS_REV_SQD_25",
        "A_Evt_Easter_XXII_Shamanic_Healing_Grounds",
        "kp_{15}",
        "A_Evt_Golden_Palace",
        "INS_KP_AW_20",
        "runeshards-1_{2}",  //instantname_value-or-""{quantity}-or-""-if-quantity==1
        "A_Evt_Easter_XXII_Rod_of_Ascleptius",
        "INS_UNIT_TG_HM_10",
        "A_Evt_March_XXI_Temple_of_Embers",
        "INS_RF_GRR_5",
        "A_Evt_Easter_XXII_Voice_of_the_Prophet",
        "A_Evt_March_XXI_Phoenix_Chick",
        "INS_UNIT_MA_10",
        "A_Evt_Easter_XX_Phoenix_Anatomy",
        "INS_REV_SQD_10{2}",
        "A_Evt_Easter_XXII_Shamanic_Healing_Grounds",
    ],
    
    "february_xxii_": [
        "A_Evt_February_XXII_Amuni_Bar",
        "A_Evt_June_XX_Amuni_Ship",
        "INS_UNIT_TG_LR_10",
        "A_Evt_February_XXII_Furry_Sands",
        "A_Evt_June_XX_Wood_Elf_Ship",
        "A_Evt_June_XX_Fairy_Ship",
        "INS_KP_AW_20",
        "A_Evt_June_XX_Orc_Ship",
        "A_Evt_June_XX_Elven_Ship",
        "A_Evt_Easter_Vii_FireTower",
        "INS_KP_AW_20",
        "A_Evt_February_XXII_Amuni_Bar",
        "A_Evt_Passageway",
        "INS_UNIT_TG_HR_10",
        "A_Evt_February_XXII_Desert_Watchtower",
        "INS_RF_GRR_5",
        "A_Evt_June_XX_Human_Ship",
        "A_Evt_Passageway",
        "INS_UNIT_TG_MA_10",
        "A_Evt_February_XXII_Furry_Sands",
        "A_Evt_June_XX_Dwarf_Ship",
        "A_Evt_February_XXII_Desert_Watchtower",
    ],
    
    "january_xxii_": [
        "A_Evt_June_XXI_Active_Fissure",
        "A_Evt_June_XXI_Hungry_Treasure",
        "INS_UNIT_LM_10",
        "A_Evt_July_XX_Wizard_Spell_Shop",
        "A_Evt_June_XXI_Unexpected_Morning",
        "A_Evt_July_XX_Golem_Cave",
        "A_Evt_July_XX_Astral_Crevice",
        "A_Evt_January_XXII_Ancient_Taste",
        "A_Evt_July_XX_Golem_Cave",
        "A_Evt_July_XX_Copper_Dragon",
        "A_Evt_July_XX_Mana_Crystal_Merchant",
        "INS_UNIT_HM_10",
        "A_Evt_July_XX_Copper_Dragon",
        "A_Evt_June_XXI_Hungry_Treasure",
        "A_Evt_January_XXII_Spectral_Moths",
        "A_Evt_June_XXI_Body_Transmutation",
        "A_Evt_July_XX_Wizard_Spell_Shop",
        "INS_UNIT_MA_10",
        "A_Evt_January_XXII_Spectral_Moths",
        "A_Evt_July_XX_Astral_Crevice",
        "INS_UNIT_MC_HR_10",
        "A_Evt_January_XXII_Ancient_Taste",
    ],

    "december_xxi_": [
        "A_Evt_December_XX_GoblinGiftShop",
        "A_Evt_December_XXI_Sled_Tunnel_Network",
        "A_Evt_Winter_XIX_Candy_Cane_Factory",
        "INS_UNIT_HR_10",
        "A_Evt_Winter_XIX_Ice_Track",
        "INS_KP_AW_20",
        "A_Evt_Winter_2Unicorn",
        "A_Evt_December_XXI_Snowball_Hut",
        "A_Evt_Winter_XIX_Elvenade_Distributor",
        "A_Evt_December_XX_FrozenOwlCave",
        "INS_UNIT_LR_10",
        "A_Evt_Winter_XIX_Three_Ghosts",
        "A_Evt_December_XX_GoblinSleigh",
        "A_Evt_Winter_XIX_Lemonade_Brewery",
        "A_Evt_December_XXI_Magical_Supply_Station",
        "A_Evt_Winter_XIX_Lemonade_Brewery",
        "INS_UNIT_MC_MA_10",
        "A_Evt_December_XX_GoblinSleigh",
        "A_Evt_Winter_XIX_Ice_Track",
        "A_Evt_Winter_1DailyReward",
        "INS_UNIT_LM_10",
        "A_Evt_December_XXI_Sled_Tunnel_Network",
        "A_Evt_Winter_XIX_Three_Ghosts",
        "A_Evt_Winter_XIX_Elvenade_Distributor",
        "INS_UNIT_MC_LR_10",
        "A_Evt_December_XXI_Snowball_Hut",
        "INS_RF_GRR_5",
        "A_Evt_Winter_XIX_Candy_Cane_Factory",
        "INS_KP_AW_20",
        "A_Evt_December_XXI_Magical_Supply_Station",
    ],
    
    "october_xxi_": [
        "A_Evt_October_XXI_Lost_Cemetry",
        "A_Evt_October_XX_Mausoleum_Wedding",
        "A_Evt_October_XX_Smiling_Pumpkins",
        "A_Evt_October_XX_Gargoyle_Fountain",
        "A_Evt_2Halloween_Xvii",
        "A_Evt_October_XX_Disturbed_Coffins",
        "A_Evt_October_XXI_Spirit_Moose_Family",
        "A_Evt_October_XX_Scarriage",
        "A_Evt_Halloween_XIX",
        "A_Evt_October_XXI_Phantom_Bear",
        "INS_KP_AW_20",
        "A_Evt_October_XX_Scarecrow",
        "A_Evt_October_XX_Gargoyle_Fountain",
        "INS_UNIT_MC_LM_10",
        "A_Evt_October_XXI_Lost_Cemetry",
        "A_Evt_October_XX_Smiling_Pumpkins",
        "A_Evt_October_XXI_Spirit_Moose_Family",
        "A_Evt_October_XX_Mausoleum_Wedding",
        "INS_UNIT_MC_MA_10",
        "A_Evt_October_XX_Scarecrow",
        "A_Evt_October_XX_Scarriage",
        "A_Evt_October_XXI_Phantom_Bear",
    ],
    
    "september_xxi_": [
        "A_Evt_September_XXI_Calligraphy_Class",
        "A_Evt_September_XXI_Training_Dojo",
        "petfood_1",
        "A_Evt_September_XX_Ancient_Pond_Statue",
        "A_Evt_Autumn_XVIII_Green_Pond",
        "A_Evt_September_XXI_Bamboo_Fountain",
        "A_Evt_September_XX_Kite_Outpost",
        "A_Evt_September_XXI_Bonsai_Garden",
        "A_Evt_September_XX_Prayer_Wheels",
        "A_Evt_September_XX_Firefly_Lookout",
        "INS_KP_AW_20",
        "A_Evt_Hazeltown",
        "A_Evt_Prod_Nutcracker",
        "INS_UNIT_MC_HR_10",
        "A_Evt_September_XXI_Training_Dojo",
        "A_Evt_September_XXI_Bamboo_Fountain",
        "A_Evt_September_XX_Bell_Fountain",
        "A_Evt_September_XX_Pond_Pillar",
        "INS_UNIT_MC_MA_10",
        "A_Evt_SquirrelTown",
        "A_Evt_September_XXI_Calligraphy_Class",
        "A_Evt_September_XXI_Bonsai_Garden",
    ],
    
    "july_xxi_": [
        "A_Evt_July_XXI_Leviathan_Ferry",
        "A_Evt_MM_XIX_MantaRay",
        "A_Evt_MM_XIX_Seahorse",
        "A_Evt_MM_XIX_CrabHotel",
        "A_Evt_July_XXI_Manta_Boat",
        "A_Evt_MM_XIX_Corals",
        "INS_KP_AW_10",
        "A_Evt_MM_XIX_CrabHotel",
        "A_Evt_MM_XIX_SharkTower",
        "A_Evt_July_XXI_Diving_Platform",
        "INS_UNIT_LM_15",
        "INS_RF_GRR_10",
        "A_Evt_July_XXI_Mechanical_Seahorse",
        "A_Evt_MM_XIX_Seahorse",
        "A_Evt_July_XXI_Manta_Boat",
        "A_Evt_MM_XIX_ShellSinger",
        "A_Evt_July_XXI_Diving_Platform",
        "INS_UNIT_LR_15",
        "A_Evt_MM_XIX_SharkTower",
        "INS_KP_AW_10",
        "A_Evt_MM_XIX_MantaRay",
        "A_Evt_July_XXI_Leviathan_Ferry"
    ],

    "june_xxi_": [
        "A_Evt_June_XXI_Unexpected_Morning",
        "A_Evt_July_XX_Golem_Cave",
        "INS_RF_GRR_10",
        "A_Evt_June_XXI_Body_Transmutation",
        "A_Evt_July_XX_Hedge_Beard_Treant",
        "A_Evt_July_XX_Wizard_Spell_Shop",
        "INS_UNIT_TG_LR_10",
        "A_Evt_June_XXI_Hungry_Treasure",
        "A_Evt_July_XX_Hedge_Beard_Treant",
        "A_Evt_June_XXI_Active_Fissure",
        "A_Evt_July_XX_Astral_Crevice",
        "INS_UNIT_TG_HM_10",
        "A_Evt_June_XXI_Hungry_Treasure",
        "A_Evt_July_XX_Golem_Cave",
        "A_Evt_June_XXI_Unexpected_Morning",
        "INS_KP_AW_10",
        "A_Evt_June_XXI_Active_Fissure",
        "A_Evt_July_XX_Copper_Dragon",
        "INS_UNIT_TG_HR_10",
        "A_Evt_July_XX_Mana_Crystal_Merchant",
        "INS_KP_AW_10",
        "A_Evt_June_XXI_Body_Transmutation"
    ],

    "may_xxi_": [
        "A_Evt_May_XXI_Bumblebee_Stables",
        "A_Evt_May_XXI_Blossom_Light_post",
        "INS_RF_GRR_10",
        "A_Evt_May_XX_Public_Stage",
        "INS_UNIT_TG_HR_10",
        "A_Evt_May_XXI_Faerie_Sand_Garden",
        "INS_KP_AW_10",
        "A_Evt_May_XXI_Dragonfly_Pond",
        "A_Evt_May_XXI_Petal_Bridge",
        "INS_UNIT_MC_LR_10",
        "A_Evt_May_XXI_Faerie_Inn",
        "A_Evt_May_XX_Halfling_Stage",
        "A_Evt_May_XX_Cake_Counter",
        "A_Evt_May_XX_Cotton_Candy_Magic",
        "A_Evt_May_XXI_Bumblebee_Stables",
        "A_Evt_May_XXI_Petal_Bridge",
        "INS_UNIT_MC_LM_10",
        "INS_KP_AW_10",
        "A_Evt_May_XXI_Faerie_Inn",
        "INS_UNIT_TG_MA_10",
        "A_Evt_May_XXI_Faerie_Sand_Garden",
        "A_Evt_May_XXI_Blossom_Light_post"
    ],

    "march_xxi_": [
        "A_Evt_Easter_XX_Phoenix_Lava",
        "A_Evt_March_XXI_Phoenix_Chick",
        "INS_RF_GRR_10",
        "A_Evt_March_XXI_Eggshell_Pavillon",
        "INS_UNIT_LM_15",
        "A_Evt_Easter_XX_Phoenix_Anatomy",
        "INS_KP_AW_10",
        "A_Evt_March_XXI_Temple_of_Embers",
        "A_Evt_March_XXI_Phoenix_Water_Mill",
        "A_Evt_March_XXI_Phoenix_Rider",
        "A_Evt_March_XXI_Eggshell_Shrine",
        "A_Evt_Easter_Vii_BurningEgg",
        "INS_UNIT_MC_LR_10",
        "A_Evt_Golden_Palace",
        "A_Evt_March_XXI_Phoenix_Chick",
        "A_Evt_March_XXI_Eggshell_Pavillon",
        "A_Evt_March_XXI_Phoenix_Water_Mill",
        "INS_UNIT_MC_LM_10",
        "A_Evt_March_XXI_Eggshell_Shrine",
        "INS_KP_AW_10",
        "A_Evt_March_XXI_Phoenix_Rider",
        "A_Evt_March_XXI_Temple_of_Embers"
    ],

    "february_xxi_": [
        "A_Evt_February_XXI_Elder_Snowman",
        "A_Evt_February_XXI_Yeti_Hot_Spring",
        "INS_RF_GRR_10",
        "A_Evt_Car_XIX_Elven_Wagon",
        "A_Evt_Car_XX_Deers_Golems",
        "A_Evt_Val_Balcony",
        "A_Evt_Car_XX_Halfling_Wagon",
        "A_Evt_February_XXI_Aureate_Willow",
        "A_Evt_Car_XIX_Dancing_People",
        "A_Evt_February_XXI_Dawn_Of_Spring_Shrine",
        "A_Evt_Car_XIX_Beauty_Puppet",
        "A_Evt_Car_XX_Dragon_Puppet",
        "INS_UNIT_LR_10",
        "A_Evt_Car_XIX_Orc_Wagon",
        "A_Evt_February_XXI_Sun_Loop",
        "INS_KP_AW_10",
        "A_Evt_February_XXI_Elder_Snowman",
        "A_Evt_Car_XX_Bubble_Mask",
        "A_Evt_Car_XX_Constructs_Wagon",
        "INS_UNIT_LM_10",
        "A_Evt_Car_XX_Dwarven_Wagon",
        "A_Evt_February_XXI_Lifeblood_Cone"
    ]
}
