var goods_icons = {
    "providedCulture": "<img src='https://image.ibb.co/mEtRZq/culture.png' title='Culture'>",
    "provided_population": "<img src='https://image.ibb.co/ipAZLV/population.png' title='Population'>",
    "money": "<img src='https://image.ibb.co/g5ErZq/money.png' title='Coins'><br>",
    "coins": "<img src='https://image.ibb.co/g5ErZq/money.png' title='Coins'><br>",
    "supplies": "<img src='https://image.ibb.co/gtNH7A/supplies.png' title='Supplies'><br>",
    "marble": "<img src='https://i.ibb.co/mtYStcp/good-marble-big.png' title='Marble'><br>",
    "steel": "<img src='https://i.ibb.co/Lds7D9z/good-steel-big.png' title='Steel'><br>",
    "planks": "<img src='https://i.ibb.co/r38GcfT/good-planks-big.png' title='Planks'><br>",
    "crystal": "<img src='https://i.ibb.co/C88GHJF/good-crystal-big.png' title='Crystal'><br>",
    "scrolls": "<img src='https://i.ibb.co/hsNXDsb/good-scrolls-big.png' title='Scrolls'><br>",
    "silk": "<img src='https://i.ibb.co/PcLs9hT/good-silk-big.png' title='Silk'><br>",
    "elixir": "<img src='https://i.ibb.co/VDtDYD1/good-elixir-big.png' title='Elixir'><br>",
    "magic_dust": "<img src='https://i.ibb.co/S3HKY7j/good-magic-dust-big.png' title='Magic Dust'><br>",
    "gems": "<img src='https://i.ibb.co/QCHg8Y5/good-gems-big.png' title='Gems'><br>",
    "boosted_plus_0_quality_1": "<img src='https://i.ibb.co/gvPd8Mv/boosted-plus-0-quality-1.png' title='Boosted T1'><br>",
    "boosted_plus_0_quality_2": "<img src='https://i.ibb.co/cgSyp4Z/boosted-plus-0-quality-2.png' title='Boosted T2'><br>",
    "boosted_plus_0_quality_3": "<img src='https://i.ibb.co/r4fRKKq/boosted-plus-0-quality-3.png' title='Boosted T3'><br>",
    "boosted_plus_1_quality_1": "<img src='https://image.ibb.co/bVDVDV/goods-quality-1-plus-1.png' title='Boosted T1 + 1'><br>", 
    "boosted_plus_2_quality_1": "<img src='https://i.ibb.co/sHDVsM0/goods-quality-1-plus-2.png' title='Boosted T1 + 2'><br>",
    "boosted_plus_1_quality_2": "<img src='https://i.ibb.co/2NC7h3q/goods-quality-2-plus-1.png' title='Boosted T2 + 1'><br>",
    "boosted_plus_2_quality_2": "<img src='https://i.ibb.co/dMHH2Ns/goods-quality-2-plus-2.png' title='Boosted T2 + 2'><br>",
    "boosted_plus_1_quality_3": "<img src='https://image.ibb.co/fOAi4f/goods-quality-3-plus-1.png' title='Boosted T3 + 1'><br>",
    "boosted_plus_2_quality_3": "<img src='https://i.ibb.co/9qqkPBC/goods-quality-3-plus-2.png' title='Boosted T3 + 2'><br>",
    "orcs": "<img src='https://i.ibb.co/Hn5W8XF/orcs.png' title='Orcs'><br>",
    "mana": "<img src='https://image.ibb.co/bzd1Zq/mana.png' title='Mana'><br>",
    "seeds": "<img src='https://image.ibb.co/c9JtEq/seeds.png' title='Seeds'><br>",
    "sentientmarble": "<img src='https://i.ibb.co/wRN3HJP/sentient-marble.png' title='Moonstone'><br>",
    "sentientsteel": "<img src='https://i.ibb.co/wB410LW/sentient-steel.png' title='Platinum'><br>",
    "sentientplanks": "<img src='https://i.ibb.co/HqmkSDk/sentient-wood.png' title='Elven Tree Gum'><br>",
    "sentientcrystal": "<img src='https://i.ibb.co/Gs7Gqgj/sentient-crystal.png' title='Obsidian'><br>",
    "sentientscrolls": "<img src='https://i.ibb.co/Y0Md5dV/sentient-scrolls.png' title='Arcane Ink'><br>",
    "sentientsilk": "<img src='https://i.ibb.co/wznTtMS/sentient-silk.png' title='Royale Velvet'><br>",
    "sentientelixir": "<img src='https://i.ibb.co/LzqV8H3/sentient-elixir.png' title='Silly Soap'><br>",
    "sentientmagic_dust": "<img src='https://i.ibb.co/MRCdFKn/sentient-dust.png' title='Alloy Shrooms'><br>",
    "sentientgems": "<img src='https://i.ibb.co/sWNdPJx/sentient-gems.png' title='Cosmic Bismuth'><br>",
    "boosted_sentient_plus_0_quality_1": "<img src='https://i.ibb.co/j3NHkyw/boosted-sentient-plus-0-quality-1-mini.png' title='Boosted T4'><br>",
    "boosted_sentient_plus_1_quality_1": "<img src='https://i.ibb.co/WvC1LQm/boosted-sentient-plus-1-quality-1-mini.png' title='Boosted T4 + 1'><br>",
    "boosted_sentient_plus_2_quality_1": "<img src='https://i.ibb.co/0GzFcvk/boosted-sentient-plus-2-quality-1-mini.png' title='Boosted T4 + 2'><br>",
    "boosted_sentient_plus_0_quality_2": "<img src='https://i.ibb.co/LhdP2gZ/boosted-sentient-plus-0-quality-2-mini.png' title='Boosted T5'><br>",
    "boosted_sentient_plus_1_quality_2": "<img src='https://i.ibb.co/j8C7yjz/boosted-sentient-plus-1-quality-2-mini.png' title='Boosted T5 + 1'><br>",
    "boosted_sentient_plus_2_quality_2": "<img src='https://i.ibb.co/1v3vkXS/boosted-sentient-plus-2-quality-2-mini.png' title='Boosted T5 + 2'><br>",
    "boosted_sentient_plus_0_quality_3": "<img src='https://i.ibb.co/RTFv8JX/boosted-sentient-plus-0-quality-3-mini.png' title='Boosted T6'><br>",
    "boosted_sentient_plus_1_quality_3": "<img src='' title='Boosted T6 + 1'><br>",
    "boosted_sentient_plus_2_quality_3": "<img src='https://i.ibb.co/cTBrnwH/boosted-sentient-plus-2-quality-3-mini.png' title='Boosted T6 + 2'><br>",
    "unurium": `<img src='https://i.ibb.co/5shvjhx/unurium-small.png' title='Unurium'><br>`,
    "knowledge_points": "<img src='https://i.ibb.co/CB7JkFY/knowledge-points-new.png' title='Knowledge Points'><br>",
    "broken_shards": "<img src='https://i.ibb.co/ZMBLJS3/broken-shard.png' title='Broken Shards'><br>",
    "ins_rf_cn_5": "5%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 5%'><br>",
    "ins_rf_cn_10": "10%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 10%'><br>",
    "ins_rf_cn_15": "15%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 15%'><br>",
    "ins_rf_cn_20": "20%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 20%'><br>",
    "ins_rf_cn_25": "25%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 25%'><br>",
    "ins_rf_cn_33": "33%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 33%'><br>",
    "ins_rf_cn_50": "50%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 50%'><br>",
    "ins_rf_cn_100": "100%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 100%'><br>",
    "ins_rf_spl_5": "5%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 5%'><br>",
    "ins_rf_spl_10": "10%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 10%'><br>",
    "ins_rf_spl_15": "15%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 15%'><br>",
    "ins_rf_spl_20": "20%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 20%'><br>",
    "ins_rf_spl_25": "25%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 25%'><br>",
    "ins_rf_spl_33": "33%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 33%'><br>",
    "ins_rf_spl_50": "50%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 50%'><br>",
    "ins_rf_spl_100": "100%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 100%'><br>",
    "ins_rf_grr_5": "5%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 5%'><br>",
    "ins_rf_grr_10": "10%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 10%'><br>",
    "ins_rf_grr_15": "15%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 15%'><br>",
    "ins_rf_grr_20": "20%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 20%'><br>",
    "ins_rf_grr_25": "25%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 25%'><br>",
    "ins_rf_grr_33": "33%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 33%'><br>",
    "ins_rf_grr_50": "50%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 50%'><br>",
    "ins_rf_grr_100": "100%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 100%'><br>",
    "INS_KP_AW_1": "1 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 1'><br>",
    "INS_KP_AW_3": "3 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 3'><br>",
    "INS_KP_AW_5": "5 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 5'><br>",
    "INS_KP_AW_7": "7 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 7'><br>",
    "INS_KP_AW_10": "10 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 10'><br>",
    "INS_KP_AW_15": "15 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 15'><br>",
    "INS_KP_AW_20": "20 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 20'><br>",
    "INS_KP_AW_30": "30 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 30'><br>",
    "ins_rs_1": "<img src='https://i.ibb.co/s6kzbrx/ins-rs.png' title='Royal Restoration'><br>",
    "royalrestoration": "<img src='https://i.ibb.co/47B34xJ/royalrestoration.png' title='Royal Restoration'><br>",
    "mc_lm": "<img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Rider'><br>",
    "mc_lr": "<img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Ranger'><br>",
    "mc_ma": "<img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Princess'><br>",
    "tg_lm": "<img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberus'><br>",
    "tg_lr": "<img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryad'><br>",
    "tg_ma": "<img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshee'><br>",
    "mc_hr": "<img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Fainéant Frog'><br>",
    "mc_hm": "<img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guard'><br>",
    "tg_hm": "<img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warrior'><br>",
    "tg_hr": "<img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategist'><br>",
    "unit_1": "<img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Axe Barbarian'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Sword Dancer'><br>",
    "unit_2": "<img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Crossbowman'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Archer'><br>",
    "unit_3": "<img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Priest'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Sorceress'><br>",
    "unit_4": "<img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Paladin'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Treant'><br>",
    "unit_5": "<img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Mortar'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Golem'><br>",
    "spell_good_production_boost_1": "<img src='https://i.ibb.co/vz2BZbv/spell-good-production.png' title='Magical Manufactoring'><br>",
    "relic_marble": "<img src='https://i.ibb.co/sJ8pN3V/relic-marble-small.png' title='Marble Relic'><br>",
    "relic_steel": "<img src='https://i.ibb.co/DYs5LqZ/relic-steel-small.png' title='Steel Relic'><br>",
    "relic_planks": "<img src='https://i.ibb.co/rHPSK2m/relic-planks-small.png' title='Plank Relic'><br>",
    "relic_crystal": "<img src='https://i.ibb.co/LvhbTt6/relic-crystal-small.png' title='Crystal Relic'><br>",
    "relic_scrolls": "<img src='https://i.ibb.co/236qxwB/relic-scrolls-small.png' title='Scroll Relic'><br>",
    "relic_silk": "<img src='https://i.ibb.co/n0z2QMS/relic-silk-small.png' title='Silk Relic'><br>",
    "relic_elixir": "<img src='https://i.ibb.co/jzxf6qf/relic-elixir-small.png' title='Elixir Relic'><br>",
    "relic_magic_dust": "<img src='https://i.ibb.co/jH0yBYV/relic-magic-dust-small.png' title='Magic Dust Relic'><br>",
    "relic_gems": "<img src='https://i.ibb.co/k4GJyzw/relic-gems-small.png' title='Gem Relic'><br>",
    "boosted_relic_plus_0_quality_1": "<img src='https://i.ibb.co/X2YZWKD/relics-t1-small.png' title='Boosted T1 Relic'><br>",
    "boosted_relic_plus_1_quality_1": "<img src='https://i.ibb.co/X2YZWKD/relics-t1-small.png' title='Boosted T1 + 1 Relic'><br>",
    "boosted_relic_plus_2_quality_1": "<img src='https://i.ibb.co/X2YZWKD/relics-t1-small.png' title='Boosted T1 + 2 Relic'><br>",
    "boosted_relic_plus_2_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 + 2 Relic'><br>",
    "boosted_relic_plus_2_quality_3": "<img src='https://i.ibb.co/f4tttR1/relics-t3-small.png' title='Boosted T3 + 2 Relic'><br>",
    "boosted_relic_plus_0_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 Relic'><br>",
    "boosted_relic_plus_1_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 + 1 Relic'><br>",
    "craft_spell_fragments": "<img src='https://i.ibb.co/fYLXgWP/spell-fragment.png' title='Spell Fragments'><br>",
    "combiningcatalyst": "<img src='https://i.ibb.co/WnDfq7P/combining-catalyst.png' title='Combining Catalyst'><br>",
    "INS_TR_AMT_1": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 1 min'><br>",
    "INS_TR_AMT_3": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 3 min'><br>",
    "INS_TR_AMT_7": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 7 min'><br>",
    "INS_TR_AMT_10": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 10 min'><br>",
    "INS_TR_AMT_15": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 15 min'><br>",
    "INS_TR_AMT_20": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 20 min'><br>",
    "INS_TR_AMT_30": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 30 min'><br>",
    "INS_TR_AMT_45": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 45 min'><br>",
    "INS_TR_AMT_60": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 1 h'><br>",
    "INS_TR_AMT_120": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 2 h'><br>",
    "INS_TR_AMT_300": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 5 h'><br>",
    "INS_TR_AMT_480": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 8 h'><br>",
    "INS_TR_AMT_840": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 14 h'><br>",
    "INS_TR_AMT_1200": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 20 h'><br>",
    "INS_TR_AMT_2400": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 40 h'><br>",
    "daily_reward": "<img src='https://i.ibb.co/7YDJFZN/daily-reward.png' title='Daily Prize'><br>",
    "rune_shard": "<img src='https://i.ibb.co/jJ1x14f/runeshard-small.png' title='Rune Shard'><br>",
    "spell_knowledge_boost_1": "<img src='https://i.ibb.co/cxTn3yM/Spell-knowledge-boost-1-small.png' title='Inspiring Meditation'><br>",
    "random": "<img src='https://i.ibb.co/4Y4qbR1/random-questionmark.png' title='Random'><br>",
    "premium": "<img src='https://i.ibb.co/cYyST31/Premium-small.png' title='Diamonds'><br>",
    "diamonds": "<img src='https://i.ibb.co/cYyST31/Premium-small.png' title='Diamonds'><br>",
    "gr6_fertilizer": "<img src='https://i.ibb.co/pPHTWTT/gr6-fertilizer.png' title='Fertilizer'><br>",
    "gr6_apples": "<img src='https://i.ibb.co/Y7c1L9J/gr6-apple.png' title='Apple'><br>",
    "spell_neighborly_help_boost_1": "<img src='https://i.ibb.co/8BsQZ4W/Spell-neighborly-help-boost-1-small.png' title='Ensorcelled Endowment'><br>",
    "gr7_toll": "<img src='https://i.ibb.co/yB6PYm2/gr7-toll.png' title='Minerals'><br>",
    "spell_supply_production_boost_1": "<img src='https://i.ibb.co/JcGk0d7/Spell-supply-production-boost-1-small.png' title='Power of Provision'><br>",
    "gr8_gravegoods": "<img src='https://i.ibb.co/GpfW8tQ/gr8-gravegoods.png' title='Grave Goods'><br>",
    "b_gr8_aw1_shards": "<img src='https://i.ibb.co/b3YfVpy/b-gr8-aw1-shards.png' title='Rune Shard for Pyramid of Purification'><br>",
    "b_gr8_aw2_shards": "<img src='https://i.ibb.co/Z6gcjn4/b-gr8-aw2-shards.png' title='Rune Shard for Lighthouse of good Neighborhood'><br>",
    "gr9_constructzero": "<img src='https://i.ibb.co/Gdkh3tQ/gr9-constructzero.png' title='c001-F_Basic'><br>",
    "gr9_constructa": "<img src='https://i.ibb.co/fDBXrxx/gr9-constructa.png' title='c724-d_Breeze'><br>",
    "gr9_constructc": "<img src='https://i.ibb.co/tBKqhgJ/gr9-constructc.png' title='c408-b_Mechatron'><br>",
    "gr9_constructb": "<img src='https://i.ibb.co/CbzHP94/gr9-constructb.png' title='c331-m_Blossom'><br>",
    "gr9_constructd": "<img src='https://i.ibb.co/nzLSHMg/gr9-constructd.png' title='c259-h_Shepherd'><br>",
    "gr9_elvenarin": "<img src='https://i.ibb.co/ykhzkKw/gr9-elvenarin.png' title='Elvenarin'><br>",
    "gr9_humanium": "<img src='https://i.ibb.co/kxDzSm4/gr9-humanium.png' title='Humanium'><br>",
    "gr9_elvarium": "<img src='https://i.ibb.co/wJ4CZfQ/gr9-elvarium.png' title='Elvarium'><br>",
    "b_gr9_aw1_shards": "<img src='https://i.ibb.co/cgJgpbH/b-gr9-aw1-shards.png' title='Rune Shard for D111 - Timewarp'><br>",
    "b_gr9_aw2_shards": "<img src='https://i.ibb.co/hXsWbSR/b-gr9-aw2-shards.png' title='Rune Shard for D222 - Simia Sapiens'><br>",
    "spell_teleport_1": "<img src='https://i.ibb.co/G53d8kw/Spell-Teleport-small.png' title='Teleport'><br>",
    "spell_pet_food_1": "<img src='https://i.ibb.co/58fnvtJ/pet-food-small.png' title='Pet Food'><br>",
    "b_gr10_aw1_shards": "<img src='https://i.ibb.co/B6cTs5S/b-gr10-aw1-shards.png' title='Rune Shard for Vortex of Storage'><br>",
    "b_gr10_aw2_shards": "<img src='https://i.ibb.co/nr2YsH1/b-gr10-aw2-shards.png' title='Rune Shard for Thermal Springs of Youth'><br>",
    "b_gr11_aw1_shards": "<img src='https://i.ibb.co/6ZqDpy6/b-gr11-aw1-shards.png' title='Rune Shard for Spire Library'><br>",
    "b_gr11_aw2_shards": "<img src='https://i.ibb.co/4KW0Vnr/b-gr11-aw2-shards.png' title='Rune Shard for Tournament Arena'><br>",
    "ch17_luxuries": "<img src='https://i.ibb.co/P4gVCFy/ch17-luxuries.png' title='Luxurious Luxuries'><br>",
    "ch17_artifacts": "<img src='https://i.ibb.co/F78mpLp/ch17-artifacts.png' title='Antique Artifacts'><br>",
    "ch17_delicacies": "<img src='https://i.ibb.co/QcFxvbR/ch17-delicacies.png' title='Delicious Delicacies'><br>",
    "b_ch17_aw1_shards": "<img src='https://i.ibb.co/B3ZYhZ6/b-ch17-aw1-shards.png' title='Rune Shard for Dragon Ark'><br>",
    "b_ch17_aw2_shards": "<img src='https://i.ibb.co/cQ55cpw/b-ch17-aw2-shards.png' title='Rune Shard for Oracle of Fortune'><br>",
    "ch18_fire": "<img src='https://i.ibb.co/YdV5CL7/ch18-fire.png' title='Fire Elementals'><br>",
    "ch18_water": "<img src='https://i.ibb.co/2NgbLCS/ch18-water.png' title='Water Elementals'><br>",
    "ch18_wind": "<img src='https://i.ibb.co/v1tGqGx/ch18-wind.png' title='Wind Elementals'><br>",
    "ch18_earth": "<img src='https://i.ibb.co/vq6WCW2/ch18-earth.png' title='Earth Elementals'><br>",
    "ch18_badge": "<img src='https://i.ibb.co/f0pd5Qk/ch18-badge.png' title='Badge of Team Spirit'><br>",
    "b_ch18_aw1_shards": "<img src='https://i.ibb.co/BKrD5zt/b-ch18-aw1-shards.png' title='Rune Shard for Shrine of the Champions'><br>",
    "b_ch18_aw2_shards": "<img src='https://i.ibb.co/JCWGPGs/b-ch18-aw2-shards.png' title='Rune Shard for Temple of Spirits'><br>",
    "crafting_slots_refresh": "<img src='https://i.ibb.co/MBGNBL9/Sipof-Clarity-small.png' title='Sip of Clarity'><br>",
    "ch19_magic1": "<img src='https://i.ibb.co/b7qh27Z/ch19-magic1.png' title='White Magic'><br>",
    "ch19_magic2": "<img src='https://i.ibb.co/c1PXS1v/ch19-magic2.png' title='Black Magic'><br>",
    "ch19_creatures1": "<img src='https://i.ibb.co/v33tCFC/ch19-creatures1.png' title='Creature of the Light'><br>",
    "ch19_creatures2": "<img src='https://i.ibb.co/QnKVhbn/ch19-creatures2.png' title='Creature of the Night'><br>",
    "ascendedmarble": "<img src='https://i.ibb.co/pZtPMZ6/ascendedmarble.png' title='Primordial Minerals'><br>",
    "ascendedsteel": "<img src='https://i.ibb.co/XXm5hc5/ascendedsteel.png' title='Ignited Ingots'><br>",
    "ascendedplanks": "<img src='https://i.ibb.co/YPd0YnB/ascendedplanks.png' title='Scholarly Sprouts'><br>",
    "ascendedcrystal": "<img src='https://i.ibb.co/1rYyB1N/ascendedcrystal.png' title='Ethereal Aerosols'><br>",
    "ascendedscrolls": "<img src='https://i.ibb.co/RcdYQM8/ascendedscrolls.png' title='Wonder Wax'><br>",
    "ascendedsilk": "<img src='https://i.ibb.co/7p27kv6/ascendedsilk.png' title='Finest Flying Powder'><br>",
    "ascendedelixir": "<img src='https://i.ibb.co/m9Hc7V4/ascendedelixir.png' title='Spicy Spread'><br>",
    "ascendedmagic_dust": "<img src='https://i.ibb.co/G7kpP6T/ascendedmagic-dust.png' title='Genius Granule'><br>",
    "ascendedgems": "<img src='https://i.ibb.co/T4ZdXHM/ascendedgems.png' title='Marvelous Marbles'><br>",
    "boosted_ascended_plus_0_quality_1": "<img src='https://i.ibb.co/s1LZv78/boosted-t7-plus-0.png' style='width: 27px;' title='Boosted T7'><br>",
    "boosted_ascended_plus_1_quality_1": "<img src='https://i.ibb.co/PG3Nst5/boosted-t7-plus-1.png' style='width: 27px;' title='Boosted T7 + 1'><br>",
    "boosted_ascended_plus_2_quality_1": "<img src='https://i.ibb.co/dPwXvCp/boosted-t7-plus-2.png' style='width: 27px;' title='Boosted T7 + 2'><br>",
    "boosted_ascended_plus_0_quality_2": "<img src='https://cz.wiki.elvenar.com/images/7/75/G_Ascended_R.png' style='width: 27px;' title='Boosted T8'><br>",
    "boosted_ascended_plus_1_quality_2": "<img src='https://i.ibb.co/YbyYDCj/boosted-t8-plus-1.png' style='width: 27px;' title='Boosted T8 + 1'><br>",
    "boosted_ascended_plus_2_quality_2": "<img src='https://i.ibb.co/6v79yJf/boosted-t8-plus-2.png' style='width: 27px;' title='Boosted T8 + 2'><br>",
    "boosted_ascended_plus_0_quality_3": "<img src='' title='Boosted T9'><br>",
    "boosted_ascended_plus_1_quality_3": "<img src='https://i.ibb.co/7QQxqw9/boosted-t9-plus-1.png' style='width: 27px;' title='Boosted T9 + 1'><br>",
    "boosted_ascended_plus_2_quality_3": "<img src='' title='Boosted T9 + 2'><br>",
    "b_all_aw1_shards": "<img src='https://i.ibb.co/cK9Bjdm/b-all-aw1-shards.png' title='Rune Shard for Tome of Secrets'><br>",
    "b_all_aw2_shards": "<img src='https://i.ibb.co/xLSxDWr/b-all-aw2-shards.png' title='Rune Shard for Golden Abyss'><br>",
    "b_all_aw3_shards": "<img src='https://i.ibb.co/x1b3jK5/b-all-aw3-shards.png' title='Rune Shard for Endless Excavation'><br>",
    "b_all_aw4_shards": "<img src='https://i.ibb.co/3MfktmQ/b-all-aw4-shards.png' title='Rune Shard for Needles of the Tempest'><br>",
    "aw1_shards": "<img src='https://i.ibb.co/tpXSfYC/aw1-shards.png' title='Rune Shard for Martial Monastery / Sanctuary'><br>",
    "aw2_shards": "<img src='https://i.ibb.co/DfLv4x9/aw2-shards.png' title='Rune Shard for Crystal Lighthouse / Great Bell Spire'><br>",
    "b_all_aw5_shards": "<img src='https://i.ibb.co/B2d7hGW/b-all-aw5-shards.png' title='Rune Shard for Watchtower Ruins'><br>",
    "b_all_aw6_shards": "<img src='https://i.ibb.co/fd3pczy/b-all-aw6-shards.png' title='Rune Shard for Thrones of the High Men'><br>",
    "b_dwarfs_aw1_shards": "<img src='https://i.ibb.co/vYW25KJ/b-dwarfs-aw1-shards.png' title='Rune Shard for Dwarven Bulwark'><br>",
    "b_dwarfs_aw2_shards": "<img src='https://i.ibb.co/6rj4tnJ/b-dwarfs-aw2-shards.png' title='Rune Shard for Mountain Halls'><br>",
    "b_fairies_aw1_shards": "<img src='https://i.ibb.co/ZgpR0VK/b-fairies-aw1-shards.png' title='Rune Shard for Prosperity Towers'><br>",
    "b_fairies_aw2_shards": "<img src='https://i.ibb.co/3RfxPpm/b-fairies-aw2-shards.png' title='Rune Shard for Blooming Trader Guild'><br>",
    "b_orcs_aw1_shards": "<img src='https://i.ibb.co/m5ZFcnJ/b-orcs-aw1-shards.png' title='Rune Shard for Heroes' Forge'><br>",
    "b_orcs_aw2_shards": "<img src='https://i.ibb.co/YpMn60w/b-orcs-aw2-shards.png' title='Rune Shard for Shrine of the Shrewdy Shrooms'><br>",
    "b_gr4_aw1_shards": "<img src='https://i.ibb.co/0VZtLsj/b-gr4-aw1-shards.png' title='Rune Shard for Enar's Embassy'><br>",
    "b_gr4_aw2_shards": "<img src='https://i.ibb.co/BHkMFKv/b-gr4-aw2-shards.png' title='Rune Shard for Flying Academy'><br>",
    "b_gr5_aw1_shards": "<img src='https://i.ibb.co/6w3QSzP/b-gr5-aw1-shards.png' title='Rune Shard for Maze of the Dark Matter'><br>",
    "b_gr5_aw2_shards": "<img src='https://i.ibb.co/88LVJjq/b-gr5-aw2-shards.png' title='Rune Shard for Dragon Abbey'><br>",
    "b_gr6_aw1_shards": "<img src='https://i.ibb.co/k9dbSLg/b-gr6-aw1-shards.png' title='Rune Shard for Temple of the Toads'><br>",
    "b_gr6_aw2_shards": "<img src='https://i.ibb.co/y4P41xH/b-gr6-aw2-shards.png' title='Rune Shard for Elvenar Trade Center'><br>",
    "b_gr7_aw1_shards": "<img src='https://i.ibb.co/CvJGPnL/b-gr7-aw1-shards.png' title='Rune Shard for Sunset Towers'><br>",
    "b_gr7_aw2_shards": "<img src='https://i.ibb.co/473B4zP/b-gr7-aw2-shards.png' title='Rune Shard for Victory Springs'><br>",
    "INS_UNIT_LM_5": "5 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_10": "10 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_15": "15 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_25": "25 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LR_5": "5 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_10": "10 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_15": "10 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_25": "25 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_MA_5": "5 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_10": "10 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_15": "10 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_25": "25 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_HM_5": "5 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_10": "10 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_15": "10 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_25": "25 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HR_5": "5 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_10": "10 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_15": "10 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_25": "25 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_5": "5 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_10": "10 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_15": "10 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_25": "25 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_5": "5 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_10": "10 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_15": "10 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_25": "25 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_5": "5 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_10": "10 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_15": "10 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_25": "25 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_5": "5 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_10": "10 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_15": "10 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_25": "25 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_5": "5 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_10": "10 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_15": "10 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_25": "25 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_5": "5 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_10": "10 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_15": "10 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_25": "25 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_5": "5 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_10": "10 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_15": "10 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_25": "25 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_5": "5 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_10": "10 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_15": "10 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_25": "25 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_5": "5 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_10": "10 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_15": "10 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_25": "25 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_5": "5 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_10": "10 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_15": "10 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_25": "25 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_REV_SQD_5": "5%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 5%'><br>",
    "INS_REV_SQD_10": "10%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 10%'><br>",
    "INS_REV_SQD_25": "25%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 25%'><br>",
    "INS_REV_SQD_50": "50%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 50%'><br>",
    "INS_REV_SQD_75": "75%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 75%'><br>",
    "INS_REV_SQD_100": "100%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 100%'><br>",
    "badge_brewery": "<img src='https://i.ibb.co/7RDLWV6/fellowship-adventures-item1.png' title='Dwarven Brewery Badge' style='width: 28px;'><br>",
    "badge_treants": "<img src='https://i.ibb.co/RzhP0kh/fellowship-adventures-item2.png' title='Treant Guild Badge' style='width: 28px;'><br>",
    "badge_bakers": "<img src='https://i.ibb.co/xz01WV7/fellowship-adventures-item3.png' title='Bakers Guild Badge' style='width: 28px;'><br>",
    "badge_carpenters": "<img src='https://i.ibb.co/MMbn5SX/fellowship-adventures-item4.png' title='Carpenters Guild Badge' style='width: 28px;'><br>",
    "luxurious_flacon": "<img src='https://i.ibb.co/0BHjcft/fellowship-adventures-item7.png' title='Luxurious Flacon' style='width: 28px;'><br>",
    "badge_blacksmith": "<img src='https://i.ibb.co/jMndZQw/fellowship-adventures-item6.png' title='Blacksmith Guild Badge' style='width: 28px;'><br>",
    "badge_farmers": "<img src='https://i.ibb.co/xH5ZVx4/fellowship-adventures-item5.png' title='Farmers Guild Badge' style='width: 28px;'><br>",
    "golden_bracelet": "<img src='https://i.ibb.co/FK8XRLW/fellowship-adventures-item8.png' title='Golden Bracelet' style='width: 28px;'><br>",
    "diamond_necklace": "<img src='https://i.ibb.co/bLqZFQc/fellowship-adventures-item9.png' title='Diamond Necklace' style='width: 28px;'><br>",
    "elegant_statue": "<img src='https://i.ibb.co/HrGBhdM/fellowship-adventures-item10.png' title='Elegant Statue' style='width: 28px;'><br>",
    "magic_potion": "<img src='https://i.ibb.co/z8b1T5b/fellowship-adventures-item12.png' title='Magic Potion' style='width: 28px;'><br>",
    "witch_hat": "<img src='https://i.ibb.co/DKK9rdv/fellowship-adventures-item13.png' title='Witch Hat' style='width: 28px;'><br>",
    "badge_wonderhelper": "<img src='https://i.ibb.co/GT4MDYf/fellowship-adventures-item14.png' title='Wonder Society Badge' style='width: 28px;'><br>",
    "money_sack": "<img src='https://i.ibb.co/8B3ZwdF/fellowship-adventures-item16.png' title='Sack of Coins' style='width: 28px;'><br>",
    "elemental_marbles": "<img src='https://i.ibb.co/sgTj589/fellowship-adventures-item20.png' title='Elemental Marbles' style='width: 28px;'><br>",
    "druid_staff": "<img src='https://i.ibb.co/BK9mwsK/fellowship-adventures-item18.png' title='Druid Staff' style='width: 28px;'><br>",
    "ghost_in_a_bottle": "<img src='https://i.ibb.co/d2jXSb7/fellowship-adventures-item17.png' title='Ghost in a bottle' style='width: 28px;'><br>",
    "badge_unit": "<img src='https://i.ibb.co/cL7BsbR/fellowship-adventures-item15.png' title='Elvarian Guard Badge' style='width: 28px;'><br>",
    "arcane_residue": "<img src='https://i.ibb.co/qDXppMz/fellowship-adventures-item19.png' title='Arcane Residue' style='width: 28px;'><br>",
    "enchanted_tiara": "<img src='https://i.ibb.co/Y3xnddG/fellowship-adventures-item21.png' title='Enchanted Tiara' style='width: 28px;'><br>",
    "wand": "<img src='https://i.ibb.co/Kqk0VBJ/fellowship-adventures-item11.png' title='Wand' style='width: 28px;'><br>",
    "b_ch19_aw1_shards": "<img src='https://i.ibb.co/TRBrG90/b-ch19-aw1-shards-small.png' title='Rune Shard for Vallorian Seal Tower'><br>",
    "b_ch19_aw2_shards": "<img src='https://i.ibb.co/sPvTV3X/b-ch19-aw2-shards-small.png' title='Rune Shard for Tree of Enlightenment'><br>",
    "b_ch20_aw1_shards": "<img src='https://i.ibb.co/Yh32gVQ/b-ch20-aw1-shards-small.png' title='Rune Shard for Ancestral Resting Place'><br>",
    "b_ch20_aw2_shards": "<img src='https://i.ibb.co/0cSGf3B/b-ch20-aw2-shards-small.png' title='Rune Shard for Scouts Tavern'><br>",
    "spire_diplomacy_joker": "<img src='https://i.ibb.co/Fgkb1HS/spire-diplomacy-joker.png' title='Spectral Stone'><br>",
    "ch20_bars": "<img src='https://i.ibb.co/WDhxLt5/ch20-bars.png' title='Bars'><br>",
    "ch20_strings": "<img src='https://i.ibb.co/nsvLRj1/ch20-strings.png' title='Plucked Violins'><br>",
    "ch20_flutes": "<img src='https://i.ibb.co/g4xBWqD/ch20-flutes.png' title='Horn Flutes'><br>",
    "ch20_drums": "<img src='https://i.ibb.co/xY8V19Z/ch20-drums.png' title='Barrel Drums'><br>",
    "ch20_songs": "<img src='https://i.ibb.co/yVh5x9x/ch20-songs.png' title='Songs'><br>",
    "ch19_creatures3": "<img src='https://i.ibb.co/ZzjCHRd/ch19-creatures3.png' title='Ultimate Creatures'><br>",
    "ch19_matter3": "<img src='https://i.ibb.co/HdfmjP9/ch19-matter3.png' title='Ultimate Matter'><br>",
    "ch17_elvenarinzero": "<img src='https://i.ibb.co/L5KTdbc/ch17-elvenarinzero.png' title='Elvenarin Zero'><br>",
    "gr11_draftlaws": "<img src='https://i.ibb.co/GPPHVT6/gr11-draftlaws.png' title='Draft Laws'><br>",
    "gr11_dwarvenpropositions": "<img src='https://i.ibb.co/GF21zLW/gr11-dwarvenpropositions.png' title='Dwarven Propositions'><br>",
    "gr11_fairypropositions": "<img src='https://i.ibb.co/Dztr5kp/gr11-fairypropositions.png' title='Fairy Propositions'><br>",
    "gr11_dwarvenamendments": "<img src='https://i.ibb.co/5BcGkzG/gr11-dwarvenamendments.png' title='Dwarven Amendments'><br>",
    "gr11_fairyamendments": "<img src='https://i.ibb.co/dJPw2zS/gr11-fairyamendments.png' title='Fairy Amendments'><br>",
    "gr11_statutes": "<img src='https://i.ibb.co/nrMkBTj/gr11-statutes.png' title='Statutes'><br>",
    "gr10_ideas": "<img src='https://i.ibb.co/N6WPWdT/gr10-ideas.png' title='Ideas'><br>",
    "gr10_workforce": "<img src='https://i.ibb.co/1bdbYk2/gr10-workforce.png' title='Workforce'><br>",
    "gr10_sculptures": "<img src='https://i.ibb.co/87hhCtQ/gr10-sculptures.png' title='Sculptures'><br>",
    "gr10_constructs": "<img src='https://i.ibb.co/jrLNdQx/gr10-constructs.png' title='Constructs'><br>",
    "gr10_crystalballs": "<img src='https://i.ibb.co/nfjpGWQ/gr10-crystalballs.png' title='Crystal Balls'><br>",
    "gr10_designs": "<img src='https://i.ibb.co/qMxRqB4/gr10-designs.png' title='Designs'><br>",
    "gr10_livingpaintings": "<img src='https://i.ibb.co/xzgJC8N/gr10-livingpaintings.png' title='Living Paintings'><br>",
    "gr10_plants": "<img src='https://i.ibb.co/GQMWfnc/gr10-plants.png' title='Plants'><br>",
    "gr10_elvencollections": "<img src='https://i.ibb.co/TBHvhSf/gr10-elvencollections.png' title='Elven Collections'><br>",
    "gr10_elvenracemanifest": "<img src='https://i.ibb.co/VmZhcwF/gr10-elvenracemanifest.png' title='Elven Manifests'><br>",
    "gr10_humancollections": "<img src='https://i.ibb.co/BjPgCTJ/gr10-humancollections.png' title='Human Collections'><br>",
    "gr10_humanracemanifest": "<img src='https://i.ibb.co/wyhqJfF/gr10-humanracemanifest.png' title='Human Manifests'><br>",
    "gr8_traps": "<img src='https://i.ibb.co/9rDWLzP/gr8-traps.png' title='Traps'><br>",
    "gr7_essence": "<img src='https://i.ibb.co/T8W848k/gr7-essence.png' title='Elvenar Essence'><br>",
    "gr6_bread": "<img src='https://i.ibb.co/9c4VZWg/gr6-bread.png' title='Tingle Bread'><br>",
    "gr6_soup": "<img src='https://i.ibb.co/PZ28Xk3/gr6-soup.png' title='Savvy Soup'><br>",
    "gr6_jam": "<img src='https://i.ibb.co/DpNff46/gr6-jam.png' title='Jolly Jelly'><br>",
    "gr5_arcanealchemists": "<img src='https://i.ibb.co/5GSDs5H/gr5-arcanealchemists.png' title='Arcane Alchemists'><br>",
    "gr5_arcanenecromancers": "<img src='https://i.ibb.co/Cz3CKYr/gr5-arcanenecromancers.png' title='Arcane Necromancers'><br>",
    "gr5_necroalchemists": "<img src='https://i.ibb.co/6vhw6pM/gr5-necroalchemists.png' title='Alchemy Necromancers'><br>",
    "gr4_woodghosts": "<img src='https://i.ibb.co/Fn7dDDg/gr4-woodghosts.png' title='Wood Ghosts'><br>",
    "gr4_windchimes": "<img src='https://i.ibb.co/7kj1Gsd/gr4-windchimes.png' title='Wind Chimes'><br>",
    "gr4_treantsprouts": "<img src='https://i.ibb.co/6sKhkVN/gr4-treantsprouts.png' title='Treant Sprouts'><br>",
    "orcs_shroomofwisdom": "<img src='https://i.ibb.co/R6sPM2C/orcs-shroomofwisdom.png' title='Shroom of Wisdom'><br>",
    "orcs_loot": "<img src='https://i.ibb.co/6PpfWCr/orcs-loot.png' title='Loot'><br>",
    "fairies_ambrosia": "<img src='https://i.ibb.co/RNYFPCM/fairies-ambrosia.png' title='Ambrosia'><br>",
    "fairies_soma": "<img src='https://i.ibb.co/HhNn4wN/fairies-soma.png' title='Night Essence'><br>",
    "dwarfs_granite": "<img src='https://i.ibb.co/Y7V2ncW/dwarfs-granite.png' title='Granite'><br>",
    "dwarfs_copper": "<img src='https://i.ibb.co/yPP187V/dwarfs-copper.png' title='Copper'><br>",
    "ch21_prey": "<img src='https://i.ibb.co/yQzzDV9/ch21-prey.png' title='Prey'><br>",
    "ch21_scales": "<img src='https://i.ibb.co/4jwScbt/ch21-scales.png' title='Sea Serpent Scales'><br>",
    "ch21_oblations3": "<img src='https://i.ibb.co/94nHZww/ch21-oblations3.png' title='Dangerous Oblations'><br>",
    "ch21_shells": "<img src='https://i.ibb.co/LpS3Qn1/ch21-shells.png' title='Lizard Shells'><br>",
    "ch21_dragon": "<img src='https://i.ibb.co/0r2pV6q/ch21-dragon.png' title='Dragon Glass'><br>",
    "ch21_oblations2": "<img src='https://i.ibb.co/FDr8WKK/ch21-oblations2.png' title='Messy Oblations'><br>",
    "ch21_art": "<img src='https://i.ibb.co/Y7NG7DG/ch21-art.png' title='Orcish Art'><br>",
    "ch21_oblations1": "<img src='https://i.ibb.co/Vp0mwnk/ch21-oblations1.png' title='Rude Oblations'><br>",
    "ch21_oblations4": "<img src='https://i.ibb.co/h7JrXWt/ch21-oblations4.png' title='Noble Oblations'><br>",
    "work": "<img src='https://i.ibb.co/Y8km2P4/work.png' title='Community Work'><br>",
    "b_ch21_aw1_shards": "<img src='https://i.ibb.co/qMP2TGV/b-ch21-aw1-shards.png' title='Rune Shard for Maman Le Prés Antique Shop'><br>",
    "b_ch21_aw2_shards": "<img src='https://i.ibb.co/xMRdtx1/b-ch21-aw2-shards.png' title='Rune Shard for Vallorian School of Sorcery'><br>",
}

var xlImages = {
    "crafting_slots_refresh": "https://i.ibb.co/q76HpVv/crafting-slots-refresh.png",
    "royalrestoration": "https://i.ibb.co/4YLRxLh/royalrestoration.png",
    "orcs": "https://i.ibb.co/Bck5YrS/orcs.png",
    "mana": "https://i.ibb.co/7GpMCkM/mana.png",
    "seeds": "https://i.ibb.co/YfQr505/seeds.png",
    "unurium": "https://i.ibb.co/hM40T65/unurium.png",
    "work": "https://i.ibb.co/KKQ5YFv/work.png",
}