var quests = {
    "october_xxii_": [
        "Vykonaj 4x susedskú výpomoc",
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 4 VB",
        "Vyrob 4x produkt ľubovoľnej manufaktury (3-hodinový) + vyrob 3x košík jedla",
        "Získaj 1x spojovací činidlo ALEBO preskúmaj 1 provinciu + vyrob 2x pokročilé nástroje",
        "Vyrob 3x produkt ľubovoľnej manufaktury (9-hodinový) ALEBO vyrob nejaké množstvo ľubovoľného zboží + získaj 8 relikvií",
        "Vykonaj 7x susedskú výpomoc + vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži",
        "Vyrob 3x chlieb + vylepši 1 budovu na level 5 alebo vyšší ALEBO získaj 200x úlomky kouzel",
        "Použi 1x ľubovoľné kúzlo + získaj 4 relikvie",
        "Vyrob 2x pokročilé nástroje + vyrob 4x produkt ľubovoľnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Použi 1x ľubovoľné kúzlo ALEBO vyrieš 2 strety na mape vyjednávaním + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrob 3x košík jedla ALEBO získaj nejaké množstvo mincí + utrať 10 VB",
        "Vyrob 7x obyčajné nástroje + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrieš 3 strety na mape vyjednávaním ALEBO trénuj nejaké množstvo jednotiek + vyrob 8x nápoje ALEBO získaj 8 relikvií",
        "Utrať 12 VB ALEBO vyrob nejaké množstvo ľubovoľného zboží + vyrob 6x chlieb ALEBO vyrieš 1 provinciu",
        "Vykonaj 7x susedskú výpomoc + utrať 4 VB",
        "Vylepši 1 budovu na level 5 alebo vyšší ALEBO vyrob 3x košík jedla + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži",
        "Vyrieš 3 strety na mape bojom ALEBO vyrieš 3 strety na mape vyjednávaním + vyrob 4x produkt ľubovoľnej manufaktury (3-hodinový) ALEBO vyrob 9x chlieb",
        "Vyrob 3x produkt ľubovoľnej manufaktury (9-hodinový) + obchoduj 1x u obchodníka",
        "Preskúmaj 1 provinciu ALEBO získaj 8 relikvií + vytvor 2x ponuku na trhu",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži ALEBO použi 1x krmení + vyrob 2x pokročilé nástroje",
        "Utrať 8 VB + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrob 4x pokročilé nástroje ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 8 VB",
        "Získaj 600x úlomky kouzel + utrať 8 VB",
        "Získaj 15-18x opar vidění ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrob 8x pokročilé nástroje + použi 2-3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo ľubovoľného zboží + utrať 12 VB",
        "Vyrob 3x košík jedla ALEBO vyrieš 1 provinciu + kúp 12 VB",
        "Vyrob 14x obyčajné nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 12 VB",
        "Získaj 8 relikvií + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrob nejaké množstvo zásob + obchoduj 4x u obchodníka",
        "Získaj nejaké množstvo mincí + vyrob 6x chlieb",
        "Trénuj nejaké množstvo jednotiek ALEBO vyrob 6x produkt ľubovoľnej manufaktury (3-hodinový) + utrať 15 VB",
        "Vyrieš 4 strety na mape vyjednávaním ALEBO vyrieš 4 strety na mape bojom + kúp 8 VB",
        "Vyrob nejaké množstvo ľubovoľného zboží ALEBO vylepši 2 budovy na level 5 alebo vyšší + utrať 12 VB",
        "Získaj 4 relikvie + vyrob nejaké množstvo zásob",
        "Vyrob 10x obyčajné nástroje + vyrob 4x produkt ľubovoľnej manufaktury (9-hodinový)",
        "Vyskúmaj 1 technológiu ALEBO získaj 10-12x opar vidění + utrať 16 VB",
        "Preskúmaj 1 provinciu ALEBO získaj 10-12x opar vidění + utrať 8 VB",
        "Vyrob nejaké množstvo ľubovoľného zboží + získaj nejaké množstvo mincí",
        "Vyrob 4x pokročilé nástroje + získaj 400x úlomky kouzel",
        "Získaj 3x ľubovoľné kúzlo ALEBO použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 12 relikvií + vyrob 6x produkt ľubovoľnej manufaktury (3-hodinový)",
        "Použi 2-3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 8 VB + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Preskúmaj 1 provinciu ALEBO získaj 400x úlomky kouzel + kúp 8 VB",
        "Získaj 2x spojovací činidlo + vyrob 4x košík jedla",
        "Trénuj nejaké množstvo jednotiek ALEBO vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob 17x obyčajné nástroje",
        "Preskúmaj 1 provinciu ALEBO získaj 2x spojovací činidlo + vyrob nejaké množstvo ľubovoľného zboží ALEBO získaj 20-24x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 16 relikvií + vyrob 6x produkt ľubovoľnej manufaktury (9-hodinový) ALEBO získaj 3x spojovací činidlo",
        "Vyrob 17x obyčajné nástroje + vyrob 8x pokročilé nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + použi 2-3x ľubovoľné kúzlo",
        "Získaj 800x úlomky kouzel + vyskúmaj 1 technológiu ALEBO získaj 25-30x opar vidění",
        "Získaj 5x ľubovoľné kúzlo ALEBO použi 5x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vyrob nejaké množstvo ľubovoľného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + získaj 2x ľubovoľné kúzlo ALEBO získaj 3x spojovací činidlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 20-24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 2-3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyrob 17x obyčajné nástroje + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob 2x sada nástrojov",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob 4x košík jedla ALEBO preskúmaj 1 provinciu",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrieš 1 provinciu ALEBO získaj 3x spojovací činidlo",
        "Vyrob 6x produkt ľubovoľnej manufaktury (3-hodinový) + získaj nejaké množstvo mincí",
        "Získaj 800x úlomky kouzel + získaj 20-24x opar vidění ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo zásob + preskúmaj 1 provinciu ALEBO získaj 2x ľubovoľné kúzlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 3x spojovací činidlo ALEBO získaj 16 relikvií + vyrob nejaké množstvo ľubovoľného zboží",
        "Vyskúmaj 1 technológiu ALEBO získaj 25-30x opar vidění + získaj 2-3x ľubovoľné kúzlo",
        "Utrať 20 VB + získaj 1000x úlomky kouzel",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 2x ľubovoľné kúzlo ALEBO získaj 3x spojovací činidlo",
    ],
    "autumn_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 8 VB",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 7x obyčajné nástroje",
        "Použi 1x ľubovoľné kúzlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 2x pokročilé nástroje",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Použi 1x ľubovoľné kúzlo ALEBO vyrieš 2 strety na mape vyjednávaním + vyrob nejaké množstvo štandardného zboží",
        "Vyrob 3x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový) + utrať 10 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 6x chlieb",
        "Vyrieš 3 strety na mape vyjednávaním ALEBO trénuj nejaké množstvo jednotiek + vyrob 8x nápoje ALEBO získaj 8 relikvií",
        "Utrať 12 VB ALEBO vyrob nejaké množstvo štandardného zboží + vyrob 6x chlieb ALEBO vyrieš 1 provinciu",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vyrob 3x košík jedla + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži",
        "Vyrieš 3 strety na mape bojom ALEBO vyrieš 3 strety na mape vyjednávaním + vyrob 3x produkt základnej manufaktury (3-hodinový) ALEBO vyrob 9x chlieb",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x košík jedla",
        "Trénuj nejaké množstvo jednotiek ALEBO preskúmaj 1 provinciu + vyrob 2x pokročilé nástroje",
        "Vyrieš 4 strety na mape ALEBO vylepši 1 budovu na level 5 alebo vyšší + získaj 8 relikvií",
        "Získaj nejaké množstvo mincí + vyrob 3x chlieb",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži + vyrob nejaké množstvo štandardného zboží ALEBO preskúmaj 1 provinciu",
        "Vyrob 7x obyčajné nástroje ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 8 VB",
        "Získaj 4 relikvie + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo zásob + obchoduj 2x u obchodníka",
        "Získaj nejaké množstvo mincí + vyrob 6x chlieb",
        "Trénuj nejaké množstvo jednotiek ALEBO vyrob 4x produkt základnej manufaktury (3-hodinový) + utrať 5 VB",
        "Vyrieš 6 stretov na mape ALEBO získaj 15-18x opar vidění + kúp 8 VB",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vylepši 2 budovy na level 5 alebo vyšší + utrať 12 VB",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 10-12x opar vidění + utrať 16 VB",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Získaj 15-18x opar vidění ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + použi 2-3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Preskúmaj 1 provinciu ALEBO vyrieš 1 provinciu + kúp 12 VB",
        "Získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob 3x košík jedla",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 2x spojovací činidlo ALEBO kúp 16 VB",
        "Vyrob nejaké množstvo štandardného zboží",
        "Vyskúmaj 1 technológiu ALEBO získaj 15-18x opar vidění + získaj 8 relikvií",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 8 VB",
        "Použi 2-3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 8 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 8 VB",
        "Získaj 12 relikvií + vyrob 4x košík jedla",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + utrať 8 VB",
        "Vyrob nejaké množstvo štandardného zboží + získaj nejaké množstvo mincí",
        "Vyrob 4x pokročilé nástroje + získaj 8 relikvií",
        "Vyrob 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 15-18x opar vidění",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrieš 1 provinciu ALEBO získaj 3x spojovací činidlo",
        "Vyrob 6x produkt základnej manufaktury (3-hodinový) + získaj nejaké množstvo mincí",
        "Získaj 16 relikvií + získaj 20-24x opar vidění ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + preskúmaj 1 provinciu ALEBO získaj 2x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 20-24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 2-3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob 2x sada nástrojov",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vykonaj 13x susedskú výpomoc",
        "Získaj 3x spojovací činidlo ALEBO získaj 16 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Získaj 20-24x opar vidění ALEBO získaj 2x spojovací činidlo + vyrob nejaké množstvo zásob",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob 6x produkt základnej manufaktury (9-hodinový)",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + použi 2-3x ľubovoľné kúzlo",
        "Použi 1-2x krmení ALEBO získaj 16 relikvií + získaj 800x úlomky kouzel",
        "Preskúmaj 1 provinciu ALEBO získaj 3x spojovací činidlo",
        "Kúp 12 VB + získaj 15-18x opar vidění",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vylepši 2 budovy na level 5 alebo vyšší + použi 2-3x ľubovoľné kúzlo",
        "Získaj 3x spojovací činidlo ALEBO získaj 25-30x opar vidění + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo zásob + utrať 20 VB",
        "Získaj 16 relikvií ALEBO získaj 3x spojovací činidlo",
        "Použi 3-4x ľubovoľné kúzlo + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
    ],
    "august_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 4x nápoje",
        "Utrať 8 VB",
        "Vykonaj 4x susedskú výpomoc",
        "Vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x košík jedla",
        "Trénuj nejaké množstvo jednotiek ALEBO preskúmaj 1 provinciu + vyrob 2x pokročilé nástroje",
        "Vyrieš 4 strety na mape ALEBO vylepši 1 budovu na level 5 alebo vyšší + získaj 8 relikvií",
        "Získaj nejaké množstvo mincí + vyrob 3x chlieb",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži + vyrob nejaké množstvo základného zboží ALEBO preskúmaj 1 provinciu",
        "Vyrob 7x obyčajné nástroje ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 8 VB",
        "Získaj 4 relikvie + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo základného zboží + obchoduj 2x u obchodníka",
        "Utrať 8 VB + vyrob 6x chlieb",
        "Trénuj nejaké množstvo jednotiek ALEBO vyrob 3x produkt základnej manufaktury (9-hodinový) + utrať 5 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 2x pokročilé nástroje",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Použi 1x ľubovoľné kúzlo ALEBO vyrieš 2 strety na mape vyjednávaním + vyrob nejaké množstvo štandardného zboží",
        "Vyrob 3x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový) + utrať 10 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 6x chlieb",
        "Vyrieš 4 strety na mape ALEBO získaj 10-12x opar vidění + kúp 8 VB",
        "Vyrob nejaké množstvo základného zboží ALEBO vylepši 1 budovu na level 5 alebo vyšší + utrať 8 VB",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 15-18x opar vidění + utrať 8 VB",
        "Vyrob nejaké množstvo základného zboží + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Získaj 12 relikvií + vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + obchoduj 5x u obchodníka ALEBO získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob 8x pokročilé nástroje ALEBO získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 20 VB",
        "Vyrob nejaké množstvo základného zboží + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 6 stretov vo veži ALEBO vyrieš 6 stretov na mape + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 15-18x opar vidění + získaj 16 relikvií",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob 12x chlieb ALEBO preskúmaj 1 provinciu",
        "Použi 3x ľubovoľné kúzlo + vykonaj 10x susedskú výpomoc",
        "Získaj nejaké množstvo jednotiek ALEBO získaj nejaké množstvo mincí + utrať 12 VB",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 600x úlomky kouzel",
        "Kúp 8 VB + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + získaj 2x spojovací činidlo ALEBO získaj 20-24x opar vidění",
        "Získaj 1x ľubovoľné kúzlo ALEBO získaj 600x úlomky kouzel + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo základného zboží ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 16 VB",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Získaj 800x úlomky kouzel + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + obchoduj 3x u obchodníka",
        "Vyskúmaj 1 technológiu ALEBO získaj 20-24x opar vidění + utrať 16 VB",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + použi 3x ľubovoľné kúzlo",
        "Použi 2x krmení ALEBO získaj 20 relikvií + získaj 800x úlomky kouzel",
        "Preskúmaj 1 provinciu ALEBO získaj 3x spojovací činidlo",
        "Kúp 12 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vykonaj 13x susedskú výpomoc",
        "Získaj 3x spojovací činidlo ALEBO získaj 20 relikvií + vyrob nejaké množstvo základného zboží",
        "Získaj 20-24x opar vidění ALEBO získaj 2x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob 6x produkt základnej manufaktury (9-hodinový)",
        "Trénuj nejaké množstvo jednotiek ALEBO získaj 20-24x opar vidění + vyrob nejaké množstvo štandardného zboží",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo základného zboží ALEBO získaj 20-24x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 20 relikvií + vyrob nejaké množstvo základného zboží ALEBO získaj 3x spojovací činidlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob 8x pokročilé nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 20 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO použi 2x krmení + utrať 20 VB",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 20-24x opar vidění",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vylepši 2 budovy na level 5 alebo vyšší ALEBO získaj 3x spojovací činidlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 20-24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 2-3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
    ],
    "july_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 8 VB",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 7x obyčajné nástroje",
        "Použi 1x ľubovoľné kúzlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 2x pokročilé nástroje",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Použi 2x požehnání na jednotky ALEBO vyrieš 2 strety na mape vyjednávaním + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 4x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový) + utrať 10 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 6x chlieb",
        "Získaj 200x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + získaj 2x spojovací činidlo ALEBO vyrieš 2 strety na mape bojom",
        "Utrať 8 VB ALEBO vyrob 6x produkt základnej manufaktury (3-hodinový) + získaj 12x opar vidění ALEBO získaj 4 relikvie",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vyrob 3x košík jedla + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži",
        "Získaj 6x opar vidění ALEBO vyrieš 3 strety na mape vyjednávaním + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x košík jedla",
        "Získaj 400x úlomky kouzel ALEBO preskúmaj 1 provinciu + vyrob 2x pokročilé nástroje",
        "Vyrieš 4 strety na mape ALEBO získaj 12x opar vidění + získaj 8 relikvií",
        "Získaj nejaké množstvo mincí + vyrob 3x chlieb",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži + získaj 6x opar vidění ALEBO preskúmaj 1 provinciu",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 4 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob nejaké množstvo zásob",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 4 VB",
        "Získaj 4 relikvie + vyrob nejaké množstvo štandardného zboží",
        "Trénuj nejaké množstvo jednotiek ALEBO získaj nejaké množstvo mincí + utrať 12 VB",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 600x úlomky kouzel",
        "Kúp 8 VB + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + získaj 2x spojovací činidlo ALEBO získaj 24x opar vidění",
        "Získaj 1 ľubovoľné kúzlo ALEBO získaj 600x úlomky kouzel + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 4 strety na mape ALEBO získaj 12x opar vidění + kúp 8 VB",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vylepši 2 budovy na level 5 alebo vyšší + utrať 12 VB",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 24x opar vidění + utrať 16 VB",
        "Získaj 600x úlomky kouzel + obchoduj 3x u obchodníka",
        "Vyrob nejaké množstvo štandardného zboží ALEBO získaj 2x spojovací činidlo",
        "Získaj 800x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrob nejaké množstvo základného zboží ALEBO vyskúmaj 1 technológiu + získaj 18x opar vidění ALEBO získaj 12 relikvií",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + získaj 1x spojovací činidlo ALEBO preskúmaj 1 provinciu",
        "Vyrob nejaké množstvo základného zboží + získaj 1x ľubovoľné kúzlo ALEBO získaj 1x spojovací činidlo",
        "Získaj 12 relikvií + vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + obchoduj 3x u obchodníka ALEBO získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 16 relikvií + vylepši 1 budovu na level 5 alebo vyšší ALEBO použi 3x dešť mincí",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 12 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 1 provinciu ALEBO vyrieš 6 turnajových stretov + vyrob nejaké množstvo zásob",
        "Trénuj nejaké množstvo jednotiek ALEBO získaj 12x opar vidění + vyrob nejaké množstvo štandardného zboží",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo základného zboží ALEBO získaj 18x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 12 VB",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob 6x pokročilé nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + použi 3x ľubovoľné kúzlo",
        "Získaj 16 relikvií + vyskúmaj 1 technológiu ALEBO získaj 30x opar vidění",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vyrob nejaké množstvo štandardného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + získaj 3x ľubovoľné kúzlo",
        "Použi 2x krmení ALEBO získaj 20 relikvií + získaj 800x úlomky kouzel",
        "Preskúmaj 1 provinciu ALEBO získaj 2x spojovací činidlo",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 16 relikvií + vylepši 2 budovy na level 5 alebo vyšší ALEBO použi 4x příděl zásob",
        "Získaj 800x úlomky kouzel + obchoduj 4x u obchodníka",
        "Vyrieš 1 provinciu ALEBO vyrieš 8 turnajových stretov + vyrob nejaké množstvo zásob",
        "Vyrob 8x pokročilé nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 20 VB",
    ],
    "may_xxii_": [
        "Kúp 4 VB",
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 4 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x chlieb",
        "Získaj 1x spojovací činidlo ALEBO získaj 8 relikvií + vytvor 2x ponuku na trhu",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO použi 1x krmení + vyrob 2x pokročilé nástroje",
        "Utrať 8 VB + vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + kúp 8 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 2x košík jedla",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Použi 2x požehnání na jednotky ALEBO vyrieš 2 strety na mape vyjednávaním + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 4x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový) + utrať 10 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 2x košík jedla",
        "Získaj 200x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + získaj 1x spojovací činidlo ALEBO vyrieš 2 strety na mape bojom",
        "Utrať 8 VB ALEBO vyrob 3x produkt základnej manufaktury (3-hodinový) + získaj 12x opar vidění ALEBO získaj 4 relikvie",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Preskúmaj 1 provinciu ALEBO vyrob 3x košík jedla + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži",
        "Získaj 6x opar vidění ALEBO vyrieš 3 strety na mape vyjednávaním + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 2 strety na mape ALEBO získaj 6x opar vidění + kúp 4 VB",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + utrať 8 VB",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 18x opar vidění + získaj 400x úlomky kouzel",
        "Získaj 600x úlomky kouzel + obchoduj 3x u obchodníka",
        "Vyrob nejaké množstvo štandardného zboží + získaj 1x spojovací činidlo",
        "Získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrob nejaké množstvo základného zboží ALEBO vyskúmaj 1 technológiu + získaj 18x opar vidění ALEBO získaj 12 relikvií",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + získaj 12x opar vidění ALEBO preskúmaj 1 provinciu",
        "Vyrob nejaké množstvo základného zboží + získaj 1x ľubovoľné kúzlo ALEBO získaj 1x spojovací činidlo",
        "Získaj 12 relikvií + vyrob 9x produkt základnej manufaktury (9-hodinový)",
        "Získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo zásob",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 16 VB",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Získaj 800x úlomky kouzel + obchoduj 2x u obchodníka",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + získaj 2x spojovací činidlo",
        "Vyskúmaj 1 technológiu ALEBO získaj 12x opar vidění + utrať 16 VB",
        "Preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší + utrať 8 VB",
        "Vyrob nejaké množstvo štandardného zboží + získaj nejaké množstvo mincí",
        "Vyrob nejaké množstvo štandardného zboží + získaj 8 relikvií",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo štandardného zboží + získaj 2x ľubovoľné kúzlo ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 6 stretov vo veži ALEBO vyrieš 6 stretov na mape + vyrob nejaké množstvo zásob",
        "Vyskúmaj 1 technológiu ALEBO získaj 18x opar vidění + získaj 16 relikvií",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + vykonaj 10x susedskú výpomoc",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 12x opar vidění",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + získaj 1x spojovací činidlo",
        "Vyrob 3x produkt základnej manufaktury (9-hodinový) + získaj nejaké množstvo mincí",
        "Získaj 12 relikvií + získaj 18x opar vidění ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + preskúmaj 1 provinciu ALEBO získaj 1x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 3x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 16 relikvií + vylepši 2 budovy na level 5 alebo vyšší ALEBO použi 4x příděl zásob",
        "Získaj 800x úlomky kouzel + obchoduj 4x u obchodníka",
        "Vyrieš 1 provinciu ALEBO vyrieš 8 turnajových stretov + vyrob nejaké množstvo zásob",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + kúp 20 VB",
        "Trénuj nejaké množstvo jednotiek ALEBO získaj 18x opar vidění + vyrob nejaké množstvo štandardného zboží",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo základného zboží ALEBO získaj 24x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + použi 3x ľubovoľné kúzlo",
        "Získaj 2x spojovací činidlo ALEBO získaj 24x opar vidění + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo zásob + utrať 20 VB",
        "Získaj 16 relikvií + získaj 2x spojovací činidlo",
        "Použi 3x ľubovoľné kúzlo + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
    ],
    "easter_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 8 VB",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 7x obyčajné nástroje",
        "Použi 1x ľubovoľné kúzlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x košík jedla",
        "Vyrob 2x pokročilé nástroje + získaj 400x úlomky kouzel ALEBO preskúmaj 1 provinciu",
        "Získaj 8 relikvií + vyrieš 4 strety na mape ALEBO získaj 12x opar vidění",
        "Získaj nejaké množstvo mincí + vyrob 3x chlieb",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži + získaj 6x opar vidění ALEBO preskúmaj 1 provinciu",
        "Kúp 8 VB + vyrob 7x obyčajné nástroje ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob nejaké množstvo základného zboží",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový) + obchoduj 1x u obchodníka",
        "Utrať 8 VB + vyrob 6x chlieb",
        "Utrať 5 VB + trénuj nejaké množstvo jednotiek ALEBO vyrob 1x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 3x chlieb",
        "Vytvor 2x ponuku na trhu + získaj 1x spojovací činidlo ALEBO získaj 8 relikvií",
        "Vyrob 2x pokročilé nástroje + vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO použi 1x krmení",
        "Utrať 8 VB + vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Kúp 8 VB + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + vyrob 6x chlieb",
        "Vyrob 3x produkt základnej manufaktury (9-hodinový) + získaj 1x spojovací činidlo ALEBO získaj 4 relikvie",
        "Použi 3x ľubovoľné kúzlo + vyrob 6x pokročilé nástroje",
        "Utrať 8 VB + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety ALEBO vyrieš 2 strety vo veži + vyrob nejaké množstvo zásob",
        "Vlož 15 VB do ľubovoľného prastarého divu + trénuj nejaké množstvo jednotiek ALEBO získaj nejaké množstvo mincí",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 600x úlomky kouzel",
        "Kúp 8 VB + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + získaj 2x spojovací činidlo ALEBO získaj 24x opar vidění",
        "Vyrob nejaké množstvo štandardného zboží + získaj 1x ľubovoľné kúzlo ALEBO získaj 600x úlomky kouzel",
        "Získaj 600x úlomky kouzel + obchoduj 3x u obchodníka",
        "Vyrob nejaké množstvo základného zboží + získaj 1x spojovací činidlo",
        "Vyrob nejaké množstvo zásob + získaj 800x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrob nejaké množstvo štandardného zboží ALEBO vyskúmaj 1 technológiu + získaj 18x opar vidění ALEBO získaj 12 relikvií",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety ALEBO vyrieš 4 strety vo veži + získaj 12x opar vidění ALEBO preskúmaj 1 provinciu",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 2x spojovací činidlo ALEBO získaj 16 relikvií + vylepši 1 budovu na level 5 alebo vyšší ALEBO použi 3x dešť mincí",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Vlož 15 VB do ľubovoľného prastarého divu + vyrob nejaké množstvo základného zboží",
        "Vyrob nejaké množstvo zásob + vyrieš 1 provinciu ALEBO vyrieš 6 turnajových stretov",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + vyrob nejaké množstvo základného zboží",
        "Vyrob nejaké množstvo zásob + získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo základného zboží + utrať 20 VB",
        "Vlož 15 VB do ľubovoľného prastarého divu + trénuj nejaké množstvo jednotiek ALEBO získaj nejaké množstvo mincí",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov ALEBO vyrieš 6 stretov vo veži + získaj 600x úlomky kouzel",
        "Kúp 8 VB + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + získaj 2x spojovací činidlo ALEBO získaj 24x opar vidění",
        "Vyrob nejaké množstvo štandardného zboží + získaj 1x ľubovoľné kúzlo ALEBO získaj 600x úlomky kouzel",
        "Použi 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Získaj 1x spojovací činidlo ALEBO získaj 12 relikvií + vylepši 1 budovu na level 5 alebo vyšší ALEBO použi 3x příděl zásob",
        "Získaj 600x úlomky kouzel + obchoduj 3x u obchodníka",
        "Vyrob nejaké množstvo zásob + vyrieš 1 provinciu ALEBO vyrieš 6 turnajových stretov",
        "Kúp 16 VB + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + použi 3x ľubovoľné kúzlo",
        "Získaj 800x úlomky kouzel + použi 2x krmení ALEBO získaj 3x ľubovoľné kúzlo",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Utrať 16 VB + vyrob nejaké množstvo základného zboží",
        "Vyrob nejaké množstvo základného zboží + trénuj nejaké množstvo jednotiek ALEBO získaj 18x opar vidění",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo štandardného zboží ALEBO získaj 24x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 18x opar vidění",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + získaj 2x spojovací činidlo",
        "Vyrob 4x produkt základnej manufaktury (9-hodinový) + získaj nejaké množstvo mincí",
        "Získaj 16 relikvií + získaj 24x opar vidění ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo základného zboží + preskúmaj 1 provinciu ALEBO získaj 2x ľubovoľné kúzlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov ALEBO vyrieš 10 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 30x opar vidění",
        "Vytvor 7x ponuku na trhu + kúp 20 VB",
        "Vyrob nejaké množstvo základného zboží + preskúmaj 1 provinciu ALEBO získaj 2x spojovací činidlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov ALEBO vyrieš 8 stretov vo veži + získaj 24x opar vidění ALEBO preskúmaj 1 provinciu",
        "Vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek + vyrob nejaké množstvo základného zboží",
    ],
    "february_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 4x nápoje",
        "Utrať 8 VB",
        "Vykonaj 4x susedskú výpomoc",
        "Vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 2x košík jedla",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Vyrob 4x produkt základnej manufaktury (3-hodinový) + použi 2x ľubovoľný zesilovač ALEBO vyrieš 2 strety na mape vyjednávaním",
        "Utrať 10 VB + vyrob 4x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 strety vo veži + vyrob 2x košík jedla",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 6x chlieb",
        "Vytvor 3x ponuku na trhu + získaj 1x spojovací činidlo ALEBO získaj 4 relikvie",
        "Použi 2x ľubovoľné kúzlo + vyrob 6x pokročilé nástroje",
        "Utrať 8 VB + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety + vyrob nejaké množstvo zásob",
        "Získaj 200x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + získaj 1x spojovací činidlo ALEBO vyrieš 2 strety na mape bojom",
        "Utrať 8 VB ALEBO vyrob 6x produkt základnej manufaktury (3-hodinový) + získaj 10x opar vidění ALEBO získaj 4 relikvie",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + preskúmaj 1 provinciu ALEBO vyrob 3x košík jedla",
        "Získaj 3x ľubovoľné kúzlo + získaj 5x opar vidění ALEBO vyrieš 3 strety na mape vyjednávaním",
        "Kúp 8 VB + vyrieš 4 strety na mape ALEBO získaj 10x opar vidění",
        "Utrať 12 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 800x úlomky kouzel + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + vyrob 3x košík jedla",
        "Získaj 12 relikvií + vyrob 6x produkt základnej manufaktury (3-hodinový)",
        "Utrať 8 VB + obchoduj 4x u obchodníka",
        "Vyrob 6x produkt základnej manufaktury (3-hodinový) + použi 3x ľubovoľný zesilovač ALEBO vyrieš 3 strety na mape vyjednávaním",
        "Utrať 15 VB + vyrob 6x košík jedla ALEBO vyrob 6x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 stretov vo veži + vyrob 3x košík jedla",
        "Vyrob nejaké množstvo základného zboží + získaj 2x ľubovoľné kúzlo",
        "Získaj 12 relikvií + vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Vyrob nejaké množstvo zásob + získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Kúp 8 VB + vyrieš 4 strety na mape ALEBO získaj 10x opar vidění",
        "Utrať 12 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 800x úlomky kouzel + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + získaj nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo zásob + získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 20 VB",
        "Vytvor 4x ponuku na trhu + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + trénuj nejaké množstvo jednotiek ALEBO získaj 10x opar vidění",
        "Získaj 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Vyrob nejaké množstvo štandardného zboží + získaj 12 relikvií",
        "Utrať 8 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + získaj nejaké množstvo mincí",
        "Získaj 15x opar vidění + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + získaj 2x spojovací činidlo ALEBO získaj 15x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 8 relikvií + získaj 1x spojovací činidlo",
        "Použi 1x ľubovoľné kúzlo + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov + získaj 20x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + použi 2x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo štandardného zboží + vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Získaj 800x úlomky kouzel + použi 2x krmení ALEBO získaj 5x ľubovoľné kúzlo",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Získaj nejaké množstvo mincí + použi 2x ľubovoľné kúzlo",
        "Získaj 16 relikvií + vyskúmaj 1 technológiu ALEBO získaj 25x opar vidění",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vyrob nejaké množstvo štandardného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 15x opar vidění",
        "Získaj 2x spojovací činidlo + vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek",
        "Vytvor 4x ponuku na trhu + získaj nejaké množstvo mincí",
        "Získaj 16 relikvií + získaj 20x opar vidění ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + preskúmaj 1 provinciu ALEBO získaj 3x ľubovoľné kúzlo",
    ],
    "january_xxii_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 8 VB",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 7x obyčajné nástroje",
        "Použi 1x ľubovoľné kúzlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 3x chlieb",
        "Vytvor 2x ponuku na trhu + získaj 1x spojovací činidlo ALEBO získaj 8 relikvií",
        "Vyrob 2x pokročilé nástroje + vyrieš 3 strety na mape bojom ALEBO použi 1x krmení",
        "Utrať 8 VB + vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Kúp 8 VB + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj 200x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + získaj 1x spojovací činidlo ALEBO vyrieš 2 strety na mape bojom",
        "Utrať 8 VB ALEBO vyrob 6x produkt základnej manufaktury (3-hodinový) + získaj 10x opar vidění ALEBO získaj 4 relikvie",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + preskúmaj 1 provinciu ALEBO vyrob 3x košík jedla",
        "Získaj 3x ľubovoľné kúzlo + získaj 5x opar vidění ALEBO vyrieš 3 strety na mape vyjednávaním",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 2x košík jedla",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Vyrob 4x produkt základnej manufaktury (3-hodinový) + použi 2x požehnání na jednotky ALEBO vyrieš 2 strety na mape vyjednávaním",
        "Utrať 10 VB + vyrob 4x košík jedla ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 strety vo veži + vyrob 2x košík jedla",
        "Kúp 12 VB + vyrob 10x obyčajné nástroje ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 8 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Vyrob 6x produkt základnej manufaktury (3-hodinový) + obchoduj 3x u obchodníka",
        "Utrať 8 VB + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 15 VB + trénuj nejaké množstvo jednotiek ALEBO vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Kúp 8 VB + vyrieš 4 strety na mape ALEBO získaj 10x opar vidění",
        "Utrať 12 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 800x úlomky kouzel + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Použi 2x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Utrať 8 VB + vyrob nejaké množstvo základného zboží",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + vyrob nejaké množstvo zásob",
        "Kúp 8 VB + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj 12 relikvií + vyrob nejaké množstvo základného zboží",
        "Vyrob 3x košík jedla + získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo zásob + vyrob nejaké množstvo základného zboží", //vyrob nejaké množstvo zásob určite????
        "Získaj 8 relikvií + vyskúmaj 1 technológiu ALEBO získaj 15x opar vidění",
        "Utrať 8 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + vyrob nejaké množstvo základného zboží",
        "Vyrob nejaké množstvo zásob + získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo základného zboží + utrať 20 VB",
        "Získaj nejaké množstvo mincí + použi 2x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + vyskúmaj 1 technológiu ALEBO získaj 15x opar vidění",
        "Utrať 15 VB + trénuj nejaké množstvo jednotiek ALEBO obchoduj 4x u obchodníka",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + vyrob nejaké množstvo základného zboží",
        "Získaj nejaké množstvo mincí + použi 2x ľubovoľné kúzlo",
        "Získaj 12 relikvií + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vyrob nejaké množstvo základného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo základného zboží",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + získaj 2x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + vyskúmaj 1 technológiu ALEBO získaj 15x opar vidění",
        "Získaj 2x spojovací činidlo + vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek",
        "Vytvor 4x ponuku na trhu + získaj nejaké množstvo mincí",
        "Získaj 16 relikvií + získaj 20x opar vidění ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo základného zboží + preskúmaj 1 provinciu ALEBO získaj 3x ľubovoľné kúzlo",
        "Získaj 20x opar vidění + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo základného zboží + získaj 2x spojovací činidlo ALEBO získaj 20x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 20 VB",
        "Získaj 16 relikvií + získaj 2x spojovací činidlo",
        "Použi 2x ľubovoľné kúzlo + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo základného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Získaj 800x úlomky kouzel + použi 2x krmení ALEBO získaj 5x ľubovoľné kúzlo",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Utrať 16 VB + vyrob nejaké množstvo základného zboží",
        "Vyrob nejaké množstvo štandardného zboží + trénuj nejaké množstvo jednotiek ALEBO získaj 15x opar vidění",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo základného zboží ALEBO získaj 20x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Vyrieš 10 stretov na mape + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
    ],
    "december_xxi_": [
        "Získaj nejaké množstvo mincí",
        "Vyrob 8x nápoje",
        "Utrať 8 VB",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrob 7x obyčajné nástroje",
        "Použi 1x ľubovoľné kúzlo",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 6x chlieb",
        "Vytvor 3x ponuku na trhu + získaj 1x spojovací činidlo ALEBO získaj 4 relikvie",
        "Použi 2x ľubovoľné kúzlo + vyrob 6x pokročilé nástroje",
        "Utrať 8 VB + vyrob 2x produkt základnej manufaktury (3-hodinový)",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety + vyrob nejaké množstvo zásob",
        "Získaj 200x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek + získaj 1x spojovací činidlo ALEBO vyrieš 2 strety na mape bojom",
        "Utrať 8 VB ALEBO vyrob 6x produkt základnej manufaktury (3-hodinový) + získaj 10x opar vidění ALEBO získaj 4 relikvie",
        "Získaj nejaké množstvo mincí + utrať 4 VB",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + preskúmaj 1 provinciu ALEBO vyrob 3x košík jedla",
        "Získaj 3x ľubovoľné kúzlo + získaj 5x opar vidění ALEBO vyrieš 3 strety na mape vyjednávaním",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 turnajové strety + vyrob 2x košík jedla",
        "Získaj 4 relikvie + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 4 VB + obchoduj 3x u obchodníka",
        "Vyrob 4x produkt základnej manufaktury (3-hodinový) + použi 2x požehnání na jednotky ALEBO vyrieš 2 strety na mape vyjednávaním",
        "Utrať 10 VB + vyrob 4x košík jedla ALEBO vyrob 3x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 strety vo veži + vyrob 2x košík jedla",
        "Kúp 8 VB + vyrob 7x obyčajné nástroje ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob nejaké množstvo štandardného zboží",
        "Vyrob 2x produkt základnej manufaktury (3-hodinový) + obchoduj 1 u obchodníka",
        "Utrať 8 VB + vyrob 4x produkt základnej manufaktury (3-hodinový)",
        "Utrať 5 VB + trénuj nejaké množstvo jednotiek ALEBO vyrob 1x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 4 strety na mape ALEBO vyrieš 4 strety vo veži + vyrob 3x košík jedla",
        "Vyrob 2x košík jedla + získaj 400x úlomky kouzel ALEBO preskúmaj 1 provinciu",
        "Získaj 8 relikvií + vyrieš 4 strety na mape ALEBO získaj 10x opar vidění",
        "Získaj nejaké množstvo mincí + vyrob 3x chlieb",
        "Vyrieš 2 strety na mape ALEBO vyrieš 2 turnajové strety + získaj 5x opar vidění ALEBO preskúmaj 1 provinciu",
        "Vlož 15 VB do ľubovoľného prastarého divu + trénuj nejaké množstvo jednotiek ALEBO získaj nejaké množstvo mincí",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + získaj 600x úlomky kouzel",
        "Kúp 8 VB + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + získaj 2x spojovací činidlo ALEBO získaj 20x opar vidění",
        "Získaj 2x ľubovoľné kúzlo + vyrob nejaké množstvo štandardného zboží",
        "Kúp 8 VB + vyrieš 4 strety na mape ALEBO získaj 10x opar vidění",
        "Utrať 12 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Získaj 4 relikvie + vyrob 2x produkt základnej manufaktury (9-hodinový)",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 stretov vo veži + vyrob nejaké množstvo zásob",
        "Získaj 800x úlomky kouzel + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo zásob",
        "Získaj 12 relikvií + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo zásob + získaj 600x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 20 VB",
        "Vytvor 4x ponuku na trhu + vykonaj 7x susedskú výpomoc",
        "Vyrob nejaké množstvo zásob + trénuj nejaké množstvo jednotiek ALEBO získaj 10x opar vidění",
        "Získaj 3x ľubovoľné kúzlo + vyrob nejaké množstvo zásob",
        "Vyrob nejaké množstvo štandardného zboží + získaj 12 relikvií",
        "Utrať 8 VB + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + získaj nejaké množstvo mincí",
        "Vyrob nejaké množstvo štandardného zboží + získaj 4x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo zásob + vyrieš 6 stretov vo veži ALEBO vyrieš 4 strety na mape bojom",
        "Získaj 16 relikvií + vyskúmaj 1 technológiu ALEBO získaj 15x opar vidění",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + získaj 20x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + vykonaj 10x susedskú výpomoc",
        "Vyrob nejaké množstvo základného zboží + získaj 2x ľubovoľné kúzlo",
        "Získaj 12 relikvií + vyrob 4x produkt základnej manufaktury (9-hodinový)",
        "Vyrob nejaké množstvo zásob + získaj 400x úlomky kouzel ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 6 stretov na mape ALEBO vyrieš 6 turnajových stretov + získaj 2x spojovací činidlo",
        "Vyrob nejaké množstvo štandardného zboží + utrať 12 VB",
        "Získaj 15x opar vidění + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Vyrob nejaké množstvo štandardného zboží + získaj 2x spojovací činidlo ALEBO získaj 15x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 8 relikvií + získaj 1x spojovací činidlo",
        "Použi 1x ľubovoľné kúzlo + preskúmaj 1 provinciu ALEBO vylepši 1 budovu na level 5 alebo vyšší",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Získaj 800x úlomky kouzel + použi 2x krmení ALEBO získaj 5x ľubovoľné kúzlo",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrob nejaké množstvo štandardného zboží + trénuj nejaké množstvo jednotiek ALEBO získaj 15x opar vidění",
        "Preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší + vyrob nejaké množstvo základného zboží ALEBO získaj 20x opar vidění",
        "Vyrob nejaké množstvo zásob + utrať 16 VB",
        "Získaj 20 relikvií + získaj 2x spojovací činidlo",
        "Vyrieš 10 stretov na mape + preskúmaj 1 provinciu ALEBO vylepši 2 budovy na level 5 alebo vyšší",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov + vyrob nejaké množstvo zásob",
        "Vyrob nejaké množstvo štandardného zboží + získaj 2x spojovací činidlo ALEBO získaj 16 relikvií",
        "Vyrob nejaké množstvo zásob + vyskúmaj 1 technológiu ALEBO získaj 20x opar vidění",
        "Utrať 20 VB + získaj 1000x úlomky kouzel",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Získaj nejaké množstvo mincí + použi 2x ľubovoľné kúzlo",
        "Získaj 16 relikvií + vyskúmaj 1 technológiu ALEBO získaj 25x opar vidění",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 20 VB + vyrob nejaké množstvo štandardného zboží",
        "Získaj nejaké množstvo mincí + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
        "Vyrieš 8 stretov na mape ALEBO vyrieš 8 turnajových stretov + získaj 20x opar vidění ALEBO preskúmaj 1 provinciu",
        "Získaj nejaké množstvo mincí + získaj 2x ľubovoľné kúzlo",
        "Vyrob nejaké množstvo štandardného zboží + vyrob nejaké množstvo zásob ALEBO trénuj nejaké množstvo jednotiek",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vyrob nejaké množstvo štandardného zboží",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 turnajových stretov + vyrob nejaké množstvo zásob",
        "Utrať 16 VB + vykonaj 13x susedskú výpomoc",
        "Vyrob nejaké množstvo štandardného zboží + získaj 2x spojovací činidlo ALEBO získaj 20 relikvií",
        "Vyrob nejaké množstvo zásob + získaj 20x opar vidění ALEBO získaj 3x ľubovoľné kúzlo",
        "Vyrieš 10 stretov na mape ALEBO vyrieš 10 stretov vo veži + získaj 4x ľubovoľné kúzlo",
    ],
    "PLACEHOLDER": [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
}
