var seasonsQuests = {
    "april_xxiv_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            ["Open 3x Flavor Loot", "Kitchen event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    },
    "january_xxiv_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            ["Open 3x Flavor Loot", "Kitchen event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    },
    "october_xxiii_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            ["Open 3x Flavor Loot", "Kitchen event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    },
    "july_xxiii_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            ["Open 3x Flavor Loot", "Kitchen event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    },
    "april_xxiii_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            ["Open 3x Flavor Loot", "Kitchen event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    },
    "december_xxii_": {
        "daily": [
            "Accept 1 trade offer from the Wholesaler",
            "Donate 4 KP to your Neighbors Ancient Wonder",
            "Invest 5 KP into one of your Ancient Wonders",
            ["Win 1 Spire Encounters by Fighting", "Spire is running (>2 days left)"],
            "Collect 1 Enchantment Spell",
            ["Collect 2 City Treasures during the Event", "Event is running"],
            ["Complete 1 Dwarven Trade", "Dwarven event is running"],
            ["Explore 1 New Village in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 2 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 2x Vision Vapor",
            "Gain 1x Combining Catalyst",
            "Collect 3x Relics",
            "Gain 200x Spell Fragments",
            ["Generate 3 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 1 Spire Encounter by Negotiating", "Spire is running (>2 days left)"],
            ["Open 1 Easter Event Chest", "Easter event is running"],
            ["Open 1 Autumn Zodiac Orb", "Autumn event is running"],
            "Give 5x Neighbourly Help",
            "Place 1 Trade Offer",
            "Produce 8x product of any manufactory (3-hours)",
            "Produce 5x produkt of any manufactory (9-hours)",
            "Produce 10x Beverages",
            "Produce 8x Simple Tools",
            "Produce 7x Loaves of Bread",
            "Produce 8x Advanced Tools",
            "Produce 4x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 1x Exploration Equipment", "Tile event is running"],
            ["Solve 1x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 1x Event quests", "Event is running"],
            ["Solve 1x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 1x Easter Event quests", "Easter event is running"],
            ["Solve 1x Halloween Event quests", "Halloween event is running"],
            ["Solve 1x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 1x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 1x Spring Event quests", "Spring event is running"],
            ["Solve 3x Tournament Encounters", "Tournament is running (>2 days left)"],
            ["Solve 1x Winter Event quests", "Winter event is running"],
            "Spend 4x Knowledge Points",
            ["Swim 1x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 1x Enchantment Spells",
            "Use 1x Ensorcelled Endowment",
            "Use 1x Magical Manufacturing",
            "Use 1x Power of Provision",
            "Collect some amount of Mana",
            "Collect some amount of Seeds",
            "Collect some amount of Unurium",
        ],
        "weekly": [
            "Accept 10 trade offers from the Wholesaler",
            "Donate 38 KP to your Neighbors Ancient Wonder",
            "Invest 50 KP into one of your Ancient Wonders",
            ["Win 10 Spire Encounters by Fighting", "Spire is running"],
            "Collect 7x Enchantment Spells",
            ["Collect 20 City Treasure during the Event", "Event is running"],
            ["Complete 10x Dwarven Trade", "Dwarven event is running"],
            ["Explore 10 New Villages in Sorcerers Event", "Sorcerers event is running"],
            ["Gain 20 Adventurer Badges", "Fellowship Adventure is running"],
            "Collect a big amount of coins",
            "Collect a fair amount of Supplies",
            "Collect 20-24x Vision Vapor",
            "Gain 10x Combining Catalyst",
            "Collect 25x Relics",
            "Gain 2000x Spell Fragments",
            ["Generate 30 Game Pieces in Dwarven Event", "Dwarven event is running"],
            ["Win 10 Spire Encounters by Negotiating", "Spire is running"],
            ["Open 10 Easter Event Chests", "Easter event is running"],
            ["Open 10 Autumn Zodiac Orbs", "Autumn event is running"],
            "Give 50x Neighbourly Help",
            "Place 7x Trade Offers",
            "Produce 75x product of any manufactory (3-hours)",
            "Produce 43x produkt of any manufactory (9-hours)",
            "Produce 100x Beverages",
            "Produce 75x Simple Tools",
            "Produce 63x Loaves of Bread",
            "Produce 77x Advanced Tools",
            "Produce 40x Baskets of Groceries",
            "Collect a good amount of Ascended Goods of your choice",
            "Produce a good amount of Goods of your choice",
            "Collect a good amount of Orcs",
            "Collect a good amount of Sentient Goods of your choice",
            ["Purchase 10x Exploration Equipment", "Tile event is running"],
            ["Solve 10x Autumn Zodiac Event quests", "Autumn event is running"],
            ["Solve 10x Event quests", "Event is running"],
            ["Solve 10x Dwarven Event quests", "Dwarven event is running"],
            ["Solve 10x Easter Event quests", "Easter event is running"],
            ["Solve 10x Halloween Event quests", "Halloween event is running"],
            ["Solve 10x Elvarian Games quests", "Elvarian Games event is running"],
            ["Solve 10x Sorcerers Event quests", "Sorcerers event is running"],
            ["Solve 10x Spring Event quests", "Spring event is running"],
            ["Solve 25x Tournament Encounters", "Tournament is running"],
            ["Solve 10x Winter Event quests", "Winter event is running"],
            "Spend 40x Knowledge Points",
            ["Swim 10x Through Hoops in Elvarian Games", "Elvarian Games event is running"],
            "Recruit a big amount of units",
            "Use 13x Enchantment Spells",
            "Use 10x Ensorcelled Endowment",
            "Use 10x Magical Manufacturing",
            "Use 10x Power of Provision",
            ["Open 3x Mystery Chest on Spire of Eternity", "Spire is running"],
            "Produce 7x Toolboxes",
            ["Reach 2000 of Tournament Score", "Tournament has not started yet"],
            ["Use 3x Lucky Draw", "Dwarven event is running"],
            "Use 5x Coin Rain",
            ["Use 3x Double Reward or use 3x Magnifying Glass", "Shuffle event is running"],
            "Use 4x Pet Food",
            "Use 2x Portal Profit",
            "Use 4x Supply Windfall Instants",
            "Use 10x Time Booster Spells",
        ]
    }
}
