var prioritiesNonProduction = ["providedCulture", "provided_population"];

var prioritiesProduction = ["money", "supplies", "marble", "steel", "planks", "crystal", "scrolls", "silk", "elixir", "magic_dust", "gems",
    "boosted_plus_0_quality_1", "boosted_plus_0_quality_2", "boosted_plus_0_quality_3", "boosted_plus_1_quality_1", "boosted_plus_2_quality_1", "boosted_plus_1_quality_2", "boosted_plus_2_quality_2", "boosted_plus_1_quality_3", "boosted_plus_2_quality_3", "orcs",
    "mana", "seeds", "sentientmarble", "sentientsteel", "sentientplanks", "sentientcrystal", "sentientscrolls", "sentientsilk", "sentientelixir", "sentientmagic_dust", "sentientgems", "boosted_sentient_plus_0_quality_1", "boosted_sentient_plus_1_quality_1", "boosted_sentient_plus_2_quality_1",
    "boosted_sentient_plus_0_quality_2", "boosted_sentient_plus_1_quality_2", "boosted_sentient_plus_2_quality_2",
    "boosted_sentient_plus_0_quality_3", "boosted_sentient_plus_1_quality_3", "boosted_sentient_plus_2_quality_3",
    "unurium", "ascendedmarble", "ascendedsteel", "ascendedplanks", "ascendedcrystal", "ascendedscrolls", "ascendedsilk",
    "ascendedelixir", "ascendedmagic_dust", "ascendedgems", "boosted_ascended_plus_0_quality_1", "boosted_ascended_plus_1_quality_1",
    "boosted_ascended_plus_2_quality_1", "boosted_ascended_plus_0_quality_2", "boosted_ascended_plus_1_quality_2",
    "boosted_ascended_plus_2_quality_2", "boosted_ascended_plus_0_quality_3", "boosted_ascended_plus_1_quality_3",
    "boosted_ascended_plus_2_quality_3", "unit_1", "unit_2", "unit_3", "unit_4", "unit_5", "tg_lm", "tg_lr", "tg_ma", "tg_hm", "tg_hr",
    "mc_lm", "mc_lr", "mc_ma", "mc_hm", "mc_hr", "knowledge_points", "broken_shards",
    "relic_marble", "relic_steel", "relic_planks", "relic_crystal", "relic_scrolls", "relic_silk", "relic_elixir",
    "relic_magic_dust", "relic_gems", "boosted_relic_plus_0_quality_2", "boosted_relic_plus_1_quality_2",
    "boosted_relic_plus_2_quality_2",
    "spell_good_production_boost_1",
    "craft_spell_fragments", "spell_combining_catalyst_1",
    "ins_rf_cn_5", "ins_rf_cn_10", "ins_rf_cn_15", "ins_rf_cn_20",
    "ins_rf_cn_25", "ins_rf_cn_33", "ins_rf_cn_50", "ins_rf_cn_100", "ins_rf_spl_5", "ins_rf_spl_10", "ins_rf_spl_15",
    "ins_rf_spl_20", "ins_rf_spl_25", "ins_rf_spl_33", "ins_rf_spl_50", "ins_rf_spl_100", "ins_rf_grr_5",
    "ins_rf_grr_10", "ins_rf_grr_15", "ins_rf_grr_20", "ins_rf_grr_25", "ins_rf_grr_33", "ins_rf_grr_50", "ins_rf_grr_100",
    "INS_TR_AMT_1", "INS_TR_AMT_3", "INS_TR_AMT_7", "INS_TR_AMT_10", "INS_TR_AMT_15", 
    "INS_TR_AMT_20", "INS_TR_AMT_30", "INS_TR_AMT_45", "INS_TR_AMT_60", "INS_TR_AMT_120", 
    "INS_TR_AMT_300", "INS_TR_AMT_480", "INS_TR_AMT_840", "INS_TR_AMT_1200", "INS_TR_AMT_2400", 
    "INS_KP_AW_1", "INS_KP_AW_3", "INS_KP_AW_5", "INS_KP_AW_7", "INS_KP_AW_10", "INS_KP_AW_15", "INS_KP_AW_20",
    "INS_KP_AW_30", "ins_rs_1", "INS_REV_SQD_10", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "", "", "", "", "",
    "", "", "", "", "", "", "", "combiningcatalyst", "spire_diplomacy_joker", "spell_pet_food_1", "random" ];

var numberOfChapters = 20;

var chapters = {
    1: 'I', 2: 'II', 3: 'III', 4: 'IV', 5: 'V', 6: 'VI', 7: 'VII', 8: 'VIII', 9: 'IX', 10: 'X',
    11: 'XI', 12: 'XII', 13: 'XIII', 14: 'XIV', 15: 'XV', 16: 'XVI', 17: 'XVII', 18: 'XVIII',
    19: 'XIX', 20: 'XX'
}

var chapterNames = {
    1: 'Chapter 1', 2: 'Chapter 2', 3: 'Chapter 3', 4: 'Chapter 4', 5: 'Chapter 5', 6: 'Dwarves', 7: 'Fairies', 
    8: 'Orcs and Goblins', 9: 'Woodelves', 10: 'Sorcerers and Dragons',
    11: 'Halflings', 12: 'Elementals', 13: 'Amuni', 14: 'Constructs', 15: 'Elvenar', 16: 'Embassies', 
    17: 'Traders of Unur', 18: 'Team Spirit', 19: 'Revenge of the Exile', 20: 'The Power of Music'
}

let eventBanners = {
    "february_xxi_": "https://i.ibb.co/NLRxJ7y/EL-akcia-karneval-2021-banner.png",
    "march_xxi_": "https://i.ibb.co/m0hGLdm/EL-akcia-ve-k-noc-2021-banner.png",
    "may_xxi_": "https://i.ibb.co/tB6W7cj/EL-akcia-m-j-2021-banner.png",
    "june_xxi_": "https://i.ibb.co/8Y0N5Qn/EL-akcia-j-n-2021-banner.png",
    "july_xxi_": "https://i.ibb.co/vh3BQGv/EL-akcia-j-l-2021-banner.png",
    "september_xxi_": "https://i.ibb.co/Sv8KCqt/EL-akcia-september-2021-banner.png",
    "october_xxi_": "https://i.ibb.co/bL1jyDX/EL-akcia-halloween-2021-banner.png",
    "december_xxi_": "https://i.ibb.co/QC32rpF/EL-akcia-zima-2021-banner.png",
    "january_xxii_": "https://i.ibb.co/Wc4RLZt/EL-akcia-janu-r-2022-banner.png",
    "february_xxii_": "https://i.ibb.co/BnmPn0x/EL-akcia-febru-r-2022-banner.png",
    "easter_xxii_": "https://i.ibb.co/ZYkfV9P/EL-akcia-ve-k-noc-2022-banner.png",
    "may_xxii_": "https://i.ibb.co/F33YbJG/EL-akcia-m-j-2022-banner.png",
    "july_xxii_": "https://i.ibb.co/nw1K2Dm/EL-akcia-j-l-2022-banner.png",
    "august_xxii_": "https://i.ibb.co/XV9cdnC/EL-akcia-august-2022-banner.png",
    "autumn_xxii_": "https://i.ibb.co/8Yp9YqV/EL-akcia-september-2022-banner.png",
    "october_xxii_": "https://i.ibb.co/XxLJQ3K/EL-akcia-okt-ber-2022-banner.png",
    "december_xxii_": "https://i.ibb.co/HDK8HvH/EL-akcia-december-2022-banner.png",
    "january_xxiii_": "https://i.ibb.co/jrDGZLf/EL-akcia-janu-r-2023-banner.png",
    "february_xxiii_": "https://i.ibb.co/W6KHd3z/EL-akcia-febru-r-2023-banner.png",
}

let eventVideos = {
    "february_xxi_": "https://www.youtube.com/embed/AS2XrTrF8PM",
    "march_xxi_": "https://www.youtube.com/embed/6VoSOv1ZXFA",
    "may_xxi_": "https://www.youtube.com/embed/lQ-iFRKuFvU",
    "june_xxi_": "https://www.youtube.com/embed/doNM1AbVWt8",
    "july_xxi_": "https://www.youtube.com/embed/sWa4cT4yGIA",
    "september_xxi_": "https://www.youtube.com/embed/DTGy8Q0lnAc",
    "october_xxi_": "https://www.youtube.com/embed/LqUrW3YtDrw;https://www.youtube.com/embed/PzUHa4Bat2k",
    "december_xxi_": "https://www.youtube.com/embed/TIKU54tbdJc",
    "january_xxii_": "https://www.youtube.com/embed/NOk4Q_u3BL8",
    "february_xxii_": "https://www.youtube.com/embed/uVduxQ4yhdo;https://www.youtube.com/embed/yXV73a8pla4",
    "easter_xxii_": "https://www.youtube.com/embed/tfQa9VOXeRA",
    "may_xxii_": "https://www.youtube.com/embed/AFkAsMvABP0",
    "july_xxii_": "https://www.youtube.com/embed/GgjFAgr-pLU;https://www.youtube.com/embed/zqgJUn2kRNA",
    "august_xxii_": "https://www.youtube.com/embed/xxgTpJJw314",
    "autumn_xxii_": "https://www.youtube.com/embed/vlPzSeNLfuQ",
}

let eventBetaStarts = { // MM/DD/YYYY
    "february_xxi_": "01/24/2021",
    "march_xxi_": "03/04/2021",
    "may_xxi_": "04/15/2021",
    "june_xxi_": "05/18/2021",
    "july_xxi_": "06/24/2021",
    "september_xxi_": "08/19/2021",
    "october_xxi_": "09/30/2021",
    "december_xxi_": "11/11/2021",
    "january_xxii_": "01/06/2022",
    "february_xxii_": "02/03/2022",
    "easter_xxii_": "03/17/2022",
    "may_xxii_": "04/14/2022",
    "july_xxii_": "05/25/2022",
    "august_xxii_": "07/07/2022",
    "autumn_xxii_": "08/18/2022",
    "october_xxii_": "09/29/2022",
    "december_xxii_": "11/11/2022",
    "january_xxiii_": "01/03/2023",
    "february_xxiii_": "02/02/2023",
}

let questsLinks = {
    "december_xxi_": "bit.ly/Quests-WinterMagic2021",
    "january_xxii_": "bit.ly/ForbiddenRuins2022",
    "february_xxii_": "bit.ly/TheBuriedCity2022",
    "easter_xxii_": "bit.ly/DawnOfThePhoenix2022",
    "may_xxii_": "bit.ly/NaturallyAmazing2022",
    "july_xxii_": "bit.ly/LuckyLittleFin2022",
    "august_xxii_": "bit.ly/GatewayIntoThePast2022",
    "autumn_xxii_": "bit.ly/AutumnZodiac2022",
    "october_xxii_": "bit.ly/MischievousTherapy2022",
    "december_xxii_": "bit.ly/WinterMagic2022",
    "january_xxiii_": "bit.ly/TheSecretsOfAlchemy2023",
    "february_xxiii_": "bit.ly/TheGreatExcavation2023",
}

let eventsDurations = {
    "december_xxi_": 30,
    "january_xxii_": 22,
    "february_xxii_": 22,
    "easter_xxii_": 22,
    "may_xxii_": 22,
    "july_xxii_": 22,
    "august_xxii_": 22,
    "autumn_xxii_": 22,
    "october_xxii_": 22,
    "december_xxii_": 30,
    "january_xxiii_": 22,
    "february_xxiii_": 19,
}

let evoUpgradeCosts = {
    "A_Evt_Evo_February_XXI_Everblossom_Sleigh" : "1x Carnival Artifact",
    "A_Evt_Evo_Autumn_XIX_Bear_Brown" : "1x Bear Artifact",
    "A_Evt_Evo_Autumn_XIX_Bear_Ice" : "1x Bear Artifact",
    "A_Evt_Evo_Winter_XIX_Gingerbread_Mansion" : "1x Gingerbread Artifact",
    "A_Evt_Evo_Summer_XIX_Stonehenge" : "1x Stonehenge Artifact",
    "A_Evt_Evo_September_XX_Moon_Bear" : "1x Moon Bear Artifact",
    "A_Evt_Evo_October_XX_Witches_Hut" : "1x Witch's Hut Artifact",
    "A_Evt_Evo_May_XX_May_Tree" : "1x Festive May Tree Artifact",
    "A_Evt_Evo_March_XXI_Ashen_Phoenix" : "1x Ashen Phoenix Artifact",
    "A_Evt_Evo_MM_XIX_WaterTower" : "1x Mermaid Artifact",
    "A_Evt_Evo_July_XX_Wise_Golem" : "1x Wise Golem Artifact",
    "A_Evt_Evo_Easter_XX_Phoenix_Coldfire" : "1x Coldfire Phoenix Artifact",
    "A_Evt_Evo_Easter_XIX_Phoenix_Yellow" : "1x Phoenix Artifact",
    "A_Evt_Evo_Easter_XIX_Phoenix_Red" : "1x Phoenix Artifact",
    "A_Evt_Evo_Easter_XIX_Phoenix_Blue" : "1x Phoenix Artifact",
    "A_Evt_Evo_December_XX_Watchful_Winter_Owl" : "1x Watchful Winter Owl Artifact",
    "A_Evt_Evo_Car_XX_Burukbrak_Gaelagil" : "1x Valentines Artifact",
    "A_Evt_Evo_Autumn_XIX_Bear_Panda" : "1x Bear Artifact",
    "A_Evt_Evo_May_XXI_Queen_Fairys_Retreat": "1x Queen Faeries Retreat Artifact",
    "A_Evt_Evo_July_XXI_Triumph_of_Tides": "1x Triumph of the Tides Artifact",
    "A_Evt_Evo_September_XXI_Red_Panda_Master": "1x Red Panda Master Artifact",
    "A_Evt_Evo_October_XXI_Witch_Summoning_Circle": "1x Witch Summoning Circle Artifact",
    "A_Evt_Evo_December_XXI_Boblins_Express_Service": "1x Boblins Express Service Artifact",
    "A_Evt_Evo_February_XXII_Echoes_of_the_Forgotten": "1x Echoes of the Forgotten Artifact",
    "A_Evt_Evo_Easter_XXII_Twilight_Phoenix": "1x Twilight Phoenix Artifact",
    "A_Evt_Evo_May_XXII_Flower_Goblin_Epiphany": "1x Flower Goblin Epiphany Artifact",
    "A_Evt_Evo_July_XXII_Glory_of_the_Nimble": "1x Glory of the Nimble Artifact",
    "A_Evt_Evo_Autumn_XXII_WittyCoon": "1x Witty Raccoon Artifact",
    "A_Evt_Evo_October_XXII_Witch_Doctor": "1x Witch Doctor Artifact",
    "A_Evt_Evo_December_XXII_Chromafrost_Glacier": "1x Chromafrost Glacier Artifact",
    "A_Evt_Evo_January_XXIII_Steam_Golem": "1x Steam Golem Artifact"
}

var feedingEffectsDescriptions = {
    "A_Evt_Evo_Autumn_XIX_Bear_Brown" : `<img src="https://i.ibb.co/9rSkBkw/unit-production-boost.png">`,
    "A_Evt_Evo_Autumn_XIX_Bear_Ice" : `<img src="https://i.ibb.co/NZ1xsbt/tournament-cooldown-reduction.png">`,
    "A_Evt_Evo_September_XX_Moon_Bear" : `<img src="https://i.ibb.co/CB7JkFY/knowledge-points-new.png">`,
    "A_Evt_Evo_March_XXI_Ashen_Phoenix" : `<img src="https://i.ibb.co/cYv1Scg/EL-akcia-ve-k-noc-2019-event-currency.png">`,
    "A_Evt_Evo_Easter_XX_Phoenix_Coldfire" : `<img src="https://i.ibb.co/CB7JkFY/knowledge-points-new.png">`,
    "A_Evt_Evo_Easter_XIX_Phoenix_Yellow" : `<img src="https://i.ibb.co/s5zgfs4/goods-production.png">`,
    "A_Evt_Evo_Easter_XIX_Phoenix_Red" : `<img src="https://i.ibb.co/3TG2xv7/unit-attack-enhance.png">`,
    "A_Evt_Evo_Easter_XIX_Phoenix_Blue" : `<img src="https://i.ibb.co/J749d95/mm-boost.png">`,
    "A_Evt_Evo_December_XX_Watchful_Winter_Owl" : `<img src="https://i.ibb.co/gvPd8Mv/boosted-plus-0-quality-1.png">`,
    "A_Evt_Evo_Autumn_XIX_Bear_Panda" : `<img src="https://i.ibb.co/0YD0JRZ/boosted-quality-1.png">`,
    "A_Evt_Evo_September_XXI_Red_Panda_Master" : `<img src="https://i.ibb.co/hYXr3HW/vision-vapor-small.png">`,
    "A_Evt_Evo_Easter_XXII_Twilight_Phoenix" : `<img src="https://i.ibb.co/Yy21rpT/health-points.png">`,
    "A_Evt_Evo_Autumn_XXII_WittyCoon" : `<img src="https://i.ibb.co/s5zgfs4/goods-production.png">`,
}

var allowedFeedingMultiplicators = {
    "completedProvinces":"completed provinces",
}

var iconsImages = {
    "damage_boost":"https://i.ibb.co/3TG2xv7/unit-attack-enhance.png",
    "event_currency_1":"https://i.ibb.co/cYv1Scg/EL-akcia-ve-k-noc-2019-event-currency.png",
    "aw_hitpoints":"https://i.ibb.co/Yy21rpT/health-points.png",
    "trader_small":"https://i.ibb.co/qjRgfSK/trader-small.png",
    "time_boosted":"https://i.ibb.co/kQhsyfn/time-boosted.png",
    "training_queue_slots":"https://i.ibb.co/V30rvS3/training-queue-slots.png",
    "barrack_small_boosted":"https://i.ibb.co/zVZk0Hy/barrack-small-boosted.png",
    "mana_decay_reduction":"https://i.ibb.co/mqPfvMr/decay-mana.png",
    "seeds_decay_reduction":"https://i.ibb.co/6F4H5Wf/decay-seeds.png",
    "unurium_decay_reduction":"https://i.ibb.co/6WLCvRV/decay-unurium.png",
    "mana":"https://i.ibb.co/VxCCGww/mana-increase.png",
    "orcs":"https://i.ibb.co/V22qvDZ/orcs-increase-small.png",
}

var iconsTitles = {
    "damage_boost":"Damage Boost",
    "event_currency_1":"Event Currency",
    "aw_hitpoints":"Troops Health",
}

var buildingTypes = {
    "culture_residential" : "Culture-residential",
    "culture" : "Culture",
    "expiring" : "Expiring",
    "" : "",
    "" : ""
}

var setNames = {
    "winter_xvii" : "Winter Set",
    "easter_xviii" : "Phoenix Cult Set",
    "summer_xviii" : "Woodelvenstock Set",
    "autumn_a_xviii" : "Harvest Temple Set",
    "autumn_b_xviii" : "Shrines of Sun and Moon Set",
    "january_xviii" : "Redbeard Set",
    "winter_a_xviii" : "Winter Market Set",
    "winter_b_xviii" : "Snow Owls Set",
    "carnival_xix" : "Carnival Set",
    "crafting_1_chess" : "Magical Chess Set",
    "spire_a_library" : "Moonstone Library Set",
    "june_xx" : "Air Traders Set",
    "scroll_sorcerers" : "Pilgrim's Manor",
    "scroll_sorcerers_xxii": "Forbidden Ruins",
    "merge_dwarvengame": "Dwarven Citadel",
    "tile_amuni_xxiii": "Ancient Promise",
}

var discardBuildings = [
    "A_Evt_Expiring_NegotiationDebuff",
    "A_Evt_Expiring_OrcBuff",
    "A_Evt_Expiring_AWAssistance",
    "february_xxiii_"
]

var eventsInfoIcons = {
    "february_xxiii_": {"img_width": "28", "img_style": "margin-left: -1px; margin-right: 10px; position: relative;"},
    "january_xxiii_": {"img_width": "28", "img_style": "margin-left: -1px; margin-right: 10px; position: relative;"},
    "december_xxii_": {"img_width": "28", "img_style": "margin-left: -1px; margin-right: 10px; position: relative;"},
}

var featureFlagsInitialEvents = {
    "info_tab": "december_xxii_",
}

var baseTabsEvents = [
    {"id":"info_panel_div", "name":"Info", "img":"various", "img_width":"45", "img_style":"margin-left: -10px; margin-right: 2px; position: relative;", "href":"#info", "onclick":"info"},
    {"id":"calendar_top_div", "name":"Calendar", "img":"images/general/calendar.png", "img_width":"45", "img_style":"margin-left: -10px; margin-right: 2px; position: relative;", "href":"#calendar", "onclick":"calendar"},
    {"id":"quests_left_panel_div", "name":"Quests", "img":"images/general/event_guide.png", "img_width":"28", "img_style":"margin-left: 0px; margin-right: 10px; position: relative;", "href":"#quests", "onclick":"quests"},
] 

var additionalTabsEvents = {
    "february_xxiii_": [
        {"id":"tools", "name":"Tools", "img":"https://i.ibb.co/D70H5y5/EL-akcia-febru-r-2022-shovel.png", "img_width":"28", "img_style":"margin-left: 0px; margin-right: 10px; margin-bottom: 3px; position: relative;", "href":"#tools", "file":"tools.html", "releaseDate":"02/02/2023"},
        {"id":"strategies", "name":"Strategies", "img":"https://i.ibb.co/W2RtBts/EL-akcia-febru-r-2022-payback.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; margin-bottom: 3px; position: relative;", "href":"#strategies", "file":"strategies.html", "releaseDate":"02/02/2023"},
        {"id":"playground", "name":"Playground", "img":"https://i.ibb.co/nmkBMxB/february-xxiii-chest5.png", "img_width":"29", "img_style":"margin-left: -1px; margin-right: 10px; margin-bottom: 3px; margin-top: -4px; position: relative;", "href":"#playground", "file":"playground.html", "releaseDate":"02/20/2023"},
    ],
    "january_xxiii_": [
        {"id":"beacons", "name":"Beacons", "img":"https://i.ibb.co/VVSyYpP/january-xxiii-beacon3.png", "img_width":"29", "img_style":"margin-left: -1px; margin-right: 10px; margin-bottom: 3px; margin-top: -4px; position: relative;", "href":"#beacons", "file":"beacons.html"},
    ],
    "october_xxii_": [
        {"id":"tools", "name":"Tools", "img":"https://i.ibb.co/NWtcHK0/tool-column.png", "img_width":"28", "img_style":"margin-left: 0px; margin-right: 10px; margin-bottom: 3px; position: relative;", "href":"#tools", "file":"tools.html", "releaseDate":"10/01/2022"},
        {"id":"strategies", "name":"Strategies", "img":"https://i.ibb.co/FK9Wd7N/event-payback.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; margin-bottom: 3px; position: relative;", "href":"#strategies", "file":"strategies.html", "releaseDate":"10/03/2022"},
    ],
    "autumn_xxii_": [
        {"id":"spheres", "name":"Spheres", "img":"https://i.ibb.co/80wYmwn/EL-akcia-september-2022-chest7.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; margin-bottom: 3px; position: relative;", "href":"#spheres", "file":"spheres.html"},
    ],
    "august_xxii_": [
        {"id":"board", "name":"Board", "img":"https://i.ibb.co/7v3HmnM/EL-akcia-august-2022-piece-a4.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; position: relative;", "href":"#board", "file":"board.html"},
        {"id":"trades", "name":"Trades", "img":"https://i.ibb.co/ctjdKNc/EL-akcia-august-2022-chest-8.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; position: relative;", "href":"#trades", "file":"trades.html"},
        {"id":"pieces", "name":"Pieces", "img":"https://i.ibb.co/ZWRchkQ/EL-akcia-august-2022-piece-c3.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; position: relative;", "href":"#pieces", "file":"pieces.html"},
        {"id":"cups", "name":"Cups", "img":"https://i.ibb.co/vVMrWDx/EL-akcia-august-2022-cup-red.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; position: relative;", "href":"#cups", "file":"cups.html"},
        {"id":"cards", "name":"Cards", "img":"https://i.ibb.co/6YyLVtV/EL-akcia-august-2022-event-currency-2-big.png", "img_width":"35", "img_style":"margin-left: -5px; margin-right: 7px; position: relative;", "href":"#cards", "file":"cards.html"},
    ],
    "july_xxii_": [
        {"id":"hoops", "name":"Hoops", "img":"https://i.ibb.co/bzfprNK/EL-scroll-aquatic-truhla-6.png", "img_width":"28", "img_style":"margin-left: -1px; margin-right: 10px; position: relative;", "href":"#hoops", "file":"hoops.html"},
    ],
}

var optionsForOrderBy = [
    {"type": "buildings", "value": "all_", "text": "All"},
    {"type": "events", "value": "day", "text": "Day"},
    {"type": "buildings&events", "value": "providedCulture", "text": "Culture per square"},
    {"type": "buildings&events", "value": "provided_population", "text": "Population per square"},
    {"type": "buildings&events", "value": "money", "text": "Money per square per 1h"},
    {"type": "buildings&events", "value": "supplies", "text": "Supplies per square per 1h"},
    {"type": "buildings&events", "value": "orcs", "text": "Orcs per square per 1h"},
    {"type": "buildings&events", "value": "mana", "text": "Mana per square per 1h"},
    {"type": "buildings&events", "value": "seeds", "text": "Seeds per square per 1h"},
    {"type": "buildings&events", "value": "unurium", "text": "Unurium per square per 1h"},
]

var optionsForFilterBy = [
    {"value": "all_events", "text": "All"},
    {"value": "only&providedCulture", "text": "Culture Only"},
    {"value": "only&providedCulture&provided_population", "text": "Culture & Population Only"},
    {"value": "boosted_plus_0_quality_1|boosted_plus_1_quality_1|boosted_plus_2_quality_1|marble|steel|planks", "text": "Standard Goods T1"},
    {"value": "boosted_plus_0_quality_2|boosted_plus_1_quality_2|boosted_plus_2_quality_2|crystal|scrolls|silk", "text": "Standard Goods T2"},
    {"value": "boosted_plus_0_quality_3|boosted_plus_1_quality_3|boosted_plus_2_quality_3|elixir|magic_dust|gems", "text": "Standard Goods T3"},
    {"value": "orcs", "text": "Orcs"},
    {"value": "mana", "text": "Mana"},
    {"value": "seeds", "text": "Seeds"},
    {"value": "boosted_sentient_plus_0_quality_1|boosted_sentient_plus_1_quality_1|boosted_sentient_plus_2_quality_1|sentientmarble|sentientsteel|sentientplanks", "text": "Sentient Goods T4"},
    {"value": "boosted_sentient_plus_0_quality_2|boosted_sentient_plus_1_quality_2|boosted_sentient_plus_2_quality_2|sentientcrystal|sentientscrolls|sentientsilk", "text": "Sentient Goods T5"},
    {"value": "boosted_sentient_plus_0_quality_3|boosted_sentient_plus_1_quality_3|boosted_sentient_plus_2_quality_3|sentientelixir|sentientmagic_dust|sentientgems", "text": "Sentient Goods T6"},
    {"value": "unurium", "text": "Unurium"},
]

var flexibleRewardsIcons = {
    "frog_unurium_DP":"https://i.ibb.co/6WJvjQD/frog-unurium.png",
    "frog_mana":"https://i.ibb.co/0F5pTWq/frog-mana.png",
    "frog_runeshards2":"https://i.ibb.co/rc3ZcDm/frog-runes.png",
    "frog_runeshards1":"https://i.ibb.co/rc3ZcDm/frog-runes.png",
    "frog_grr_5":"https://i.ibb.co/JHqqq6j/frog-grr.png",
    "frog_default1":"https://i.ibb.co/VD89QDJ/frog-default1.png",
}

var goods_icons = {
    "providedCulture": "<img src='https://image.ibb.co/mEtRZq/culture.png' title='Culture'>",
    "provided_population": "<img src='https://image.ibb.co/ipAZLV/population.png' title='Population'>",
    "money": "<img src='https://image.ibb.co/g5ErZq/money.png' title='Coins'><br>",
    "coins": "<img src='https://image.ibb.co/g5ErZq/money.png' title='Coins'><br>",
    "supplies": "<img src='https://image.ibb.co/gtNH7A/supplies.png' title='Supplies'><br>",
    "marble": "<img src='https://i.ibb.co/mtYStcp/good-marble-big.png' title='Marble'><br>",
    "steel": "<img src='https://i.ibb.co/Lds7D9z/good-steel-big.png' title='Steel'><br>",
    "planks": "<img src='https://i.ibb.co/r38GcfT/good-planks-big.png' title='Planks'><br>",
    "crystal": "<img src='https://i.ibb.co/C88GHJF/good-crystal-big.png' title='Crystal'><br>",
    "scrolls": "<img src='https://i.ibb.co/hsNXDsb/good-scrolls-big.png' title='Scrolls'><br>",
    "silk": "<img src='https://i.ibb.co/PcLs9hT/good-silk-big.png' title='Silk'><br>",
    "elixir": "<img src='https://i.ibb.co/VDtDYD1/good-elixir-big.png' title='Elixir'><br>",
    "magic_dust": "<img src='https://i.ibb.co/S3HKY7j/good-magic-dust-big.png' title='Magic Dust'><br>",
    "gems": "<img src='https://i.ibb.co/QCHg8Y5/good-gems-big.png' title='Gems'><br>",
    "boosted_plus_0_quality_1": "<img src='https://i.ibb.co/gvPd8Mv/boosted-plus-0-quality-1.png' title='Boosted T1'><br>",
    "boosted_plus_0_quality_2": "<img src='https://i.ibb.co/cgSyp4Z/boosted-plus-0-quality-2.png' title='Boosted T2'><br>",
    "boosted_plus_0_quality_3": "<img src='https://i.ibb.co/r4fRKKq/boosted-plus-0-quality-3.png' title='Boosted T3'><br>",
    "boosted_plus_1_quality_1": "<img src='https://image.ibb.co/bVDVDV/goods-quality-1-plus-1.png' title='Boosted T1 + 1'><br>", 
    "boosted_plus_2_quality_1": "<img src='https://i.ibb.co/sHDVsM0/goods-quality-1-plus-2.png' title='Boosted T1 + 2'><br>",
    "boosted_plus_1_quality_2": "<img src='https://i.ibb.co/2NC7h3q/goods-quality-2-plus-1.png' title='Boosted T2 + 1'><br>",
    "boosted_plus_2_quality_2": "<img src='https://i.ibb.co/dMHH2Ns/goods-quality-2-plus-2.png' title='Boosted T2 + 2'><br>",
    "boosted_plus_1_quality_3": "<img src='https://image.ibb.co/fOAi4f/goods-quality-3-plus-1.png' title='Boosted T3 + 1'><br>",
    "boosted_plus_2_quality_3": "<img src='https://i.ibb.co/9qqkPBC/goods-quality-3-plus-2.png' title='Boosted T3 + 2'><br>",
    "orcs": "<img src='https://i.ibb.co/Hn5W8XF/orcs.png' title='Orcs'><br>",
    "mana": "<img src='https://image.ibb.co/bzd1Zq/mana.png' title='Mana'><br>",
    "seeds": "<img src='https://image.ibb.co/c9JtEq/seeds.png' title='Seeds'><br>",
    "sentientmarble": "<img src='https://i.ibb.co/wRN3HJP/sentient-marble.png' title='Moonstone'><br>",
    "sentientsteel": "<img src='https://i.ibb.co/wB410LW/sentient-steel.png' title='Platinum'><br>",
    "sentientplanks": "<img src='https://i.ibb.co/HqmkSDk/sentient-wood.png' title='Elven Tree Gum'><br>",
    "sentientcrystal": "<img src='https://i.ibb.co/Gs7Gqgj/sentient-crystal.png' title='Obsidian'><br>",
    "sentientscrolls": "<img src='https://i.ibb.co/Y0Md5dV/sentient-scrolls.png' title='Arcane Ink'><br>",
    "sentientsilk": "<img src='https://i.ibb.co/wznTtMS/sentient-silk.png' title='Royale Velvet'><br>",
    "sentientelixir": "<img src='https://i.ibb.co/LzqV8H3/sentient-elixir.png' title='Silly Soap'><br>",
    "sentientmagic_dust": "<img src='https://i.ibb.co/MRCdFKn/sentient-dust.png' title='Alloy Shrooms'><br>",
    "sentientgems": "<img src='https://i.ibb.co/sWNdPJx/sentient-gems.png' title='Cosmic Bismuth'><br>",
    "boosted_sentient_plus_0_quality_1": "<img src='https://i.ibb.co/j3NHkyw/boosted-sentient-plus-0-quality-1-mini.png' title='Boosted T4'><br>",
    "boosted_sentient_plus_1_quality_1": "<img src='https://i.ibb.co/WvC1LQm/boosted-sentient-plus-1-quality-1-mini.png' title='Boosted T4 + 1'><br>",
    "boosted_sentient_plus_2_quality_1": "<img src='https://i.ibb.co/0GzFcvk/boosted-sentient-plus-2-quality-1-mini.png' title='Boosted T4 + 2'><br>",
    "boosted_sentient_plus_0_quality_2": "<img src='https://i.ibb.co/LhdP2gZ/boosted-sentient-plus-0-quality-2-mini.png' title='Boosted T5'><br>",
    "boosted_sentient_plus_1_quality_2": "<img src='https://i.ibb.co/j8C7yjz/boosted-sentient-plus-1-quality-2-mini.png' title='Boosted T5 + 1'><br>",
    "boosted_sentient_plus_2_quality_2": "<img src='https://i.ibb.co/1v3vkXS/boosted-sentient-plus-2-quality-2-mini.png' title='Boosted T5 + 2'><br>",
    "boosted_sentient_plus_0_quality_3": "<img src='https://i.ibb.co/RTFv8JX/boosted-sentient-plus-0-quality-3-mini.png' title='Boosted T6'><br>",
    "boosted_sentient_plus_1_quality_3": "T6+1 ",
    "boosted_sentient_plus_2_quality_3": "<img src='https://i.ibb.co/cTBrnwH/boosted-sentient-plus-2-quality-3-mini.png' title='Boosted T6 + 2'><br>",
    "unurium": `<img src='https://i.ibb.co/5shvjhx/unurium-small.png' title='Unurium'><br>`,
    "knowledge_points": "<img src='https://i.ibb.co/CB7JkFY/knowledge-points-new.png' title='Knowledge Points'><br>",
    "broken_shards": "<img src='https://i.ibb.co/ZMBLJS3/broken-shard.png' title='Broken Shards'><br>",
    "ins_rf_cn_5": "5%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 5%'><br>",
    "ins_rf_cn_10": "10%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 10%'><br>",
    "ins_rf_cn_15": "15%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 15%'><br>",
    "ins_rf_cn_20": "20%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 20%'><br>",
    "ins_rf_cn_25": "25%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 25%'><br>",
    "ins_rf_cn_33": "33%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 33%'><br>",
    "ins_rf_cn_50": "50%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 50%'><br>",
    "ins_rf_cn_100": "100%<br><img src='https://image.ibb.co/dJs520/coin-rain.png' title='Coin Rain Instant 100%'><br>",
    "ins_rf_spl_5": "5%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 5%'><br>",
    "ins_rf_spl_10": "10%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 10%'><br>",
    "ins_rf_spl_15": "15%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 15%'><br>",
    "ins_rf_spl_20": "20%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 20%'><br>",
    "ins_rf_spl_25": "25%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 25%'><br>",
    "ins_rf_spl_33": "33%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 33%'><br>",
    "ins_rf_spl_50": "50%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 50%'><br>",
    "ins_rf_spl_100": "100%<br><img src='https://image.ibb.co/c8e7FL/supply-windfall.png' title='Supply Windfall Instant 100%'><br>",
    "ins_rf_grr_5": "5%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 5%'><br>",
    "ins_rf_grr_10": "10%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 10%'><br>",
    "ins_rf_grr_15": "15%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 15%'><br>",
    "ins_rf_grr_20": "20%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 20%'><br>",
    "ins_rf_grr_25": "25%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 25%'><br>",
    "ins_rf_grr_33": "33%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 33%'><br>",
    "ins_rf_grr_50": "50%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 50%'><br>",
    "ins_rf_grr_100": "100%<br><img src='https://i.ibb.co/vvxT5fD/ins-grr.png' title='Portal Profit Instant 100%'><br>",
    "INS_KP_AW_1": "1 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 1'><br>",
    "INS_KP_AW_3": "3 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 3'><br>",
    "INS_KP_AW_5": "5 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 5'><br>",
    "INS_KP_AW_7": "7 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 7'><br>",
    "INS_KP_AW_10": "10 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 10'><br>",
    "INS_KP_AW_15": "15 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 15'><br>",
    "INS_KP_AW_20": "20 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 20'><br>",
    "INS_KP_AW_30": "30 KP<br><img src='https://image.ibb.co/mqSKvL/ancient-knowledge.png' title='Ancient Knowledge Instant 30'><br>",
    "ins_rs_1": "<img src='https://i.ibb.co/s6kzbrx/ins-rs.png' title='Royal Restoration'><br>",
    "mc_lm": "<img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Rider'><br>",
    "mc_lr": "<img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Ranger'><br>",
    "mc_ma": "<img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Princess'><br>",
    "tg_lm": "<img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberus'><br>",
    "tg_lr": "<img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryad'><br>",
    "tg_ma": "<img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshee'><br>",
    "mc_hr": "<img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Fainéant Frog'><br>",
    "mc_hm": "<img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guard'><br>",
    "tg_hm": "<img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warrior'><br>",
    "tg_hr": "<img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategist'><br>",
    "unit_1": "<img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Axe Barbarian'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Sword Dancer'><br>",
    "unit_2": "<img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Crossbowman'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Archer'><br>",
    "unit_3": "<img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Priest'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Sorceress'><br>",
    "unit_4": "<img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Paladin'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Treant'><br>",
    "unit_5": "<img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Mortar'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Golem'><br>",
    "spell_good_production_boost_1": "<img src='https://i.ibb.co/vz2BZbv/spell-good-production.png' title='Magical Manufactoring'><br>",
    "relic_marble": "<img src='https://i.ibb.co/sJ8pN3V/relic-marble-small.png' title='Marble Relic'><br>",
    "relic_steel": "<img src='https://i.ibb.co/DYs5LqZ/relic-steel-small.png' title='Steel Relic'><br>",
    "relic_planks": "<img src='https://i.ibb.co/rHPSK2m/relic-planks-small.png' title='Plank Relic'><br>",
    "relic_crystal": "<img src='https://i.ibb.co/LvhbTt6/relic-crystal-small.png' title='Crystal Relic'><br>",
    "relic_scrolls": "<img src='https://i.ibb.co/236qxwB/relic-scrolls-small.png' title='Scroll Relic'><br>",
    "relic_silk": "<img src='https://i.ibb.co/n0z2QMS/relic-silk-small.png' title='Silk Relic'><br>",
    "relic_elixir": "<img src='https://i.ibb.co/jzxf6qf/relic-elixir-small.png' title='Elixir Relic'><br>",
    "relic_magic_dust": "<img src='https://i.ibb.co/jH0yBYV/relic-magic-dust-small.png' title='Magic Dust Relic'><br>",
    "relic_gems": "<img src='https://i.ibb.co/k4GJyzw/relic-gems-small.png' title='Gem Relic'><br>",
    "boosted_relic_plus_2_quality_1": "<img src='https://i.ibb.co/X2YZWKD/relics-t1-small.png' title='Boosted T1 + 2 Relic'><br>",
    "boosted_relic_plus_2_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 + 2 Relic'><br>",
    "boosted_relic_plus_2_quality_3": "<img src='https://i.ibb.co/f4tttR1/relics-t3-small.png' title='Boosted T3 + 2 Relic'><br>",
    "boosted_relic_plus_0_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 Relic'><br>",
    "boosted_relic_plus_1_quality_2": "<img src='https://i.ibb.co/hWtPCSd/relics-t2-small.png' title='Boosted T2 + 1 Relic'><br>",
    "craft_spell_fragments": "<img src='https://i.ibb.co/fYLXgWP/spell-fragment.png' title='Spell Fragments'><br>",
    "combiningcatalyst": "<img src='https://i.ibb.co/WnDfq7P/combining-catalyst.png' title='Combining Catalyst'><br>",
    "INS_TR_AMT_1": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 1 min'><br>",
    "INS_TR_AMT_3": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 3 min'><br>",
    "INS_TR_AMT_7": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 7 min'><br>",
    "INS_TR_AMT_10": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 10 min'><br>",
    "INS_TR_AMT_15": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 15 min'><br>",
    "INS_TR_AMT_20": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 20 min'><br>",
    "INS_TR_AMT_30": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 30 min'><br>",
    "INS_TR_AMT_45": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 45 min'><br>",
    "INS_TR_AMT_60": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 1 h'><br>",
    "INS_TR_AMT_120": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 2 h'><br>",
    "INS_TR_AMT_300": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 5 h'><br>",
    "INS_TR_AMT_480": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 8 h'><br>",
    "INS_TR_AMT_840": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 14 h'><br>",
    "INS_TR_AMT_1200": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 20 h'><br>",
    "INS_TR_AMT_2400": "<img src='https://i.ibb.co/8dBhcrH/ins-tr-amt-small.png' title='Time Booster 40 h'><br>",
    "daily_reward": "<img src='https://i.ibb.co/7YDJFZN/daily-reward.png' title='Daily Prize'><br>",
    "rune_shard": "<img src='https://i.ibb.co/jJ1x14f/runeshard-small.png' title='Rune Shard'><br>",
    "spell_knowledge_boost_1": "<img src='https://i.ibb.co/cxTn3yM/Spell-knowledge-boost-1-small.png' title='Inspiring Meditation'><br>",
    "random": "<img src='https://i.ibb.co/4Y4qbR1/random-questionmark.png' title='Random'><br>",
    "premium": "<img src='https://i.ibb.co/cYyST31/Premium-small.png' title='Diamonds'><br>",
    "diamonds": "<img src='https://i.ibb.co/cYyST31/Premium-small.png' title='Diamonds'><br>",
    "gr6_fertilizer": "<img src='https://i.ibb.co/pPHTWTT/gr6-fertilizer.png' title='Fertilizer'><br>",
    "gr6_apples": "<img src='https://i.ibb.co/Y7c1L9J/gr6-apple.png' title='Apple'><br>",
    "spell_neighborly_help_boost_1": "<img src='https://i.ibb.co/8BsQZ4W/Spell-neighborly-help-boost-1-small.png' title='Ensorcelled Endowment'><br>",
    "gr7_toll": "<img src='https://i.ibb.co/yB6PYm2/gr7-toll.png' title='Minerals'><br>",
    "spell_supply_production_boost_1": "<img src='https://i.ibb.co/JcGk0d7/Spell-supply-production-boost-1-small.png' title='Power of Provision'><br>",
    "gr8_gravegoods": "<img src='https://i.ibb.co/GpfW8tQ/gr8-gravegoods.png' title='Grave Goods'><br>",
    "b_gr8_aw1_shards": "<img src='https://i.ibb.co/b3YfVpy/b-gr8-aw1-shards.png' title='Rune Shard for Pyramid of Purification'><br>",
    "b_gr8_aw2_shards": "<img src='https://i.ibb.co/Z6gcjn4/b-gr8-aw2-shards.png' title='Rune Shard for Lighthouse of good Neighborhood'><br>",
    "gr9_constructzero": "<img src='https://i.ibb.co/Gdkh3tQ/gr9-constructzero.png' title='c001-F_Basic'><br>",
    "gr9_constructa": "<img src='https://i.ibb.co/fDBXrxx/gr9-constructa.png' title='c724-d_Breeze'><br>",
    "gr9_constructc": "<img src='https://i.ibb.co/tBKqhgJ/gr9-constructc.png' title='c408-b_Mechatron'><br>",
    "gr9_constructb": "<img src='https://i.ibb.co/CbzHP94/gr9-constructb.png' title='c331-m_Blossom'><br>",
    "gr9_constructd": "<img src='https://i.ibb.co/nzLSHMg/gr9-constructd.png' title='c259-h_Shepherd'><br>",
    "gr9_elvenarin": "<img src='https://i.ibb.co/ykhzkKw/gr9-elvenarin.png' title='Elvenarin'><br>",
    "gr9_humanium": "<img src='https://i.ibb.co/kxDzSm4/gr9-humanium.png' title='Humanium'><br>",
    "gr9_elvarium": "<img src='https://i.ibb.co/wJ4CZfQ/gr9-elvarium.png' title='Elvarium'><br>",
    "b_gr9_aw1_shards": "<img src='https://i.ibb.co/cgJgpbH/b-gr9-aw1-shards.png' title='Rune Shard for D111 - Timewarp'><br>",
    "b_gr9_aw2_shards": "<img src='https://i.ibb.co/hXsWbSR/b-gr9-aw2-shards.png' title='Rune Shard for D222 - Simia Sapiens'><br>",
    "spell_teleport_1": "<img src='https://i.ibb.co/G53d8kw/Spell-Teleport-small.png' title='Teleport'><br>",
    "spell_pet_food_1": "<img src='https://i.ibb.co/58fnvtJ/pet-food-small.png' title='Pet Food'><br>",
    "b_gr10_aw1_shards": "<img src='https://i.ibb.co/B6cTs5S/b-gr10-aw1-shards.png' title='Rune Shard for Vortex of Storage'><br>",
    "b_gr10_aw2_shards": "<img src='https://i.ibb.co/nr2YsH1/b-gr10-aw2-shards.png' title='Rune Shard for Thermal Springs of Youth'><br>",
    "b_gr11_aw1_shards": "<img src='https://i.ibb.co/6ZqDpy6/b-gr11-aw1-shards.png' title='Rune Shard for Spire Library'><br>",
    "b_gr11_aw2_shards": "<img src='https://i.ibb.co/4KW0Vnr/b-gr11-aw2-shards.png' title='Rune Shard for Tournament Arena'><br>",
    "ch17_luxuries": "<img src='https://i.ibb.co/P4gVCFy/ch17-luxuries.png' title='Luxurious Luxuries'><br>",
    "ch17_artifacts": "<img src='https://i.ibb.co/F78mpLp/ch17-artifacts.png' title='Antique Artifacts'><br>",
    "ch17_delicacies": "<img src='https://i.ibb.co/QcFxvbR/ch17-delicacies.png' title='Delicious Delicacies'><br>",
    "b_ch17_aw1_shards": "<img src='https://i.ibb.co/B3ZYhZ6/b-ch17-aw1-shards.png' title='Rune Shard for Dragon Ark'><br>",
    "b_ch17_aw2_shards": "<img src='https://i.ibb.co/cQ55cpw/b-ch17-aw2-shards.png' title='Rune Shard for Oracle of Fortune'><br>",
    "ch18_fire": "<img src='https://i.ibb.co/YdV5CL7/ch18-fire.png' title='Fire Elementals'><br>",
    "ch18_water": "<img src='https://i.ibb.co/2NgbLCS/ch18-water.png' title='Water Elementals'><br>",
    "ch18_wind": "<img src='https://i.ibb.co/v1tGqGx/ch18-wind.png' title='Wind Elementals'><br>",
    "ch18_earth": "<img src='https://i.ibb.co/vq6WCW2/ch18-earth.png' title='Earth Elementals'><br>",
    "ch18_badge": "<img src='https://i.ibb.co/f0pd5Qk/ch18-badge.png' title='Badge of Team Spirit'><br>",
    "b_ch18_aw1_shards": "<img src='https://i.ibb.co/BKrD5zt/b-ch18-aw1-shards.png' title='Rune Shard for Shrine of the Champions'><br>",
    "b_ch18_aw2_shards": "<img src='https://i.ibb.co/JCWGPGs/b-ch18-aw2-shards.png' title='Rune Shard for Temple of Spirits'><br>",
    "crafting_slots_refresh": "<img src='https://i.ibb.co/MBGNBL9/Sipof-Clarity-small.png' title='Sip of Clarity'><br>",
    "ch19_magic1": "<img src='https://i.ibb.co/b7qh27Z/ch19-magic1.png' title='White Magic'><br>",
    "ch19_magic2": "<img src='https://i.ibb.co/c1PXS1v/ch19-magic2.png' title='Black Magic'><br>",
    "ch19_creatures1": "<img src='https://i.ibb.co/v33tCFC/ch19-creatures1.png' title='Creature of the Light'><br>",
    "ch19_creatures2": "<img src='https://i.ibb.co/QnKVhbn/ch19-creatures2.png' title='Creature of the Night'><br>",
    "ascendedmarble": "<img src='https://i.ibb.co/pZtPMZ6/ascendedmarble.png' title='Primordial Minerals'><br>",
    "ascendedsteel": "<img src='https://i.ibb.co/XXm5hc5/ascendedsteel.png' title='Ignited Ingots'><br>",
    "ascendedplanks": "<img src='https://i.ibb.co/YPd0YnB/ascendedplanks.png' title='Scholarly Sprouts'><br>",
    "ascendedcrystal": "<img src='https://i.ibb.co/1rYyB1N/ascendedcrystal.png' title='Ethereal Aerosols'><br>",
    "ascendedscrolls": "<img src='https://i.ibb.co/RcdYQM8/ascendedscrolls.png' title='Wonder Wax'><br>",
    "ascendedsilk": "<img src='https://i.ibb.co/7p27kv6/ascendedsilk.png' title='Finest Flying Powder'><br>",
    "ascendedelixir": "<img src='' title='ascendedelixir'><br>",
    "ascendedmagic_dust": "<img src='' title='ascendedmagic_dust'><br>",
    "ascendedgems": "<img src='' title='ascendedgems'><br>",
    "boosted_ascended_plus_0_quality_1": "<img src='https://i.ibb.co/s1LZv78/boosted-t7-plus-0.png' style='width: 27px;' title='Boosted T7'><br>",
    "boosted_ascended_plus_1_quality_1": "<img src='https://i.ibb.co/PG3Nst5/boosted-t7-plus-1.png' style='width: 27px;' title='Boosted T7 + 1'><br>",
    "boosted_ascended_plus_2_quality_1": "<img src='https://i.ibb.co/dPwXvCp/boosted-t7-plus-2.png' style='width: 27px;' title='Boosted T7 + 2'><br>",
    "boosted_ascended_plus_0_quality_2": "<img src='' title='Boosted T8'><br>",
    "boosted_ascended_plus_1_quality_2": "<img src='https://i.ibb.co/YbyYDCj/boosted-t8-plus-1.png' style='width: 27px;' title='Boosted T8 + 1'><br>",
    "boosted_ascended_plus_2_quality_2": "<img src='https://i.ibb.co/6v79yJf/boosted-t8-plus-2.png' style='width: 27px;' title='Boosted T8 + 2'><br>",
    "boosted_ascended_plus_0_quality_3": "<img src='' title='Boosted T9'><br>",
    "boosted_ascended_plus_1_quality_3": "<img src='' title='Boosted T9 + 1'><br>",
    "boosted_ascended_plus_2_quality_3": "<img src='' title='Boosted T9 + 2'><br>",
    "b_all_aw1_shards": "<img src='https://i.ibb.co/cK9Bjdm/b-all-aw1-shards.png' title='Rune Shard for Tome of Secrets'><br>",
    "b_all_aw2_shards": "<img src='https://i.ibb.co/xLSxDWr/b-all-aw2-shards.png' title='Rune Shard for Golden Abyss'><br>",
    "b_all_aw3_shards": "<img src='https://i.ibb.co/x1b3jK5/b-all-aw3-shards.png' title='Rune Shard for Endless Excavation'><br>",
    "b_all_aw4_shards": "<img src='https://i.ibb.co/3MfktmQ/b-all-aw4-shards.png' title='Rune Shard for Needles of the Tempest'><br>",
    "b_all_aw5_shards": "<img src='https://i.ibb.co/B2d7hGW/b-all-aw5-shards.png' title='Rune Shard for Watchtower Ruins'><br>",
    "b_all_aw6_shards": "<img src='https://i.ibb.co/fd3pczy/b-all-aw6-shards.png' title='Rune Shard for Thrones of the High Men'><br>",
    "b_dwarfs_aw1_shards": "<img src='https://i.ibb.co/vYW25KJ/b-dwarfs-aw1-shards.png' title='Rune Shard for Dwarven Bulwark'><br>",
    "b_dwarfs_aw2_shards": "<img src='https://i.ibb.co/6rj4tnJ/b-dwarfs-aw2-shards.png' title='Rune Shard for Mountain Halls'><br>",
    "b_fairies_aw1_shards": "<img src='https://i.ibb.co/ZgpR0VK/b-fairies-aw1-shards.png' title='Rune Shard for Prosperity Towers'><br>",
    "b_fairies_aw2_shards": "<img src='https://i.ibb.co/3RfxPpm/b-fairies-aw2-shards.png' title='Rune Shard for Blooming Trader Guild'><br>",
    "b_orcs_aw1_shards": "<img src='https://i.ibb.co/m5ZFcnJ/b-orcs-aw1-shards.png' title='Rune Shard for Heroes' Forge'><br>",
    "b_orcs_aw2_shards": "<img src='https://i.ibb.co/YpMn60w/b-orcs-aw2-shards.png' title='Rune Shard for Shrine of the Shrewdy Shrooms'><br>",
    "b_gr4_aw1_shards": "<img src='https://i.ibb.co/0VZtLsj/b-gr4-aw1-shards.png' title='Rune Shard for Enar's Embassy'><br>",
    "b_gr4_aw2_shards": "<img src='https://i.ibb.co/BHkMFKv/b-gr4-aw2-shards.png' title='Rune Shard for Flying Academy'><br>",
    "b_gr5_aw1_shards": "<img src='https://i.ibb.co/6w3QSzP/b-gr5-aw1-shards.png' title='Rune Shard for Maze of the Dark Matter'><br>",
    "b_gr5_aw2_shards": "<img src='https://i.ibb.co/88LVJjq/b-gr5-aw2-shards.png' title='Rune Shard for Dragon Abbey'><br>",
    "b_gr6_aw1_shards": "<img src='https://i.ibb.co/k9dbSLg/b-gr6-aw1-shards.png' title='Rune Shard for Temple of the Toads'><br>",
    "b_gr6_aw2_shards": "<img src='https://i.ibb.co/y4P41xH/b-gr6-aw2-shards.png' title='Rune Shard for Elvenar Trade Center'><br>",
    "b_gr7_aw1_shards": "<img src='https://i.ibb.co/CvJGPnL/b-gr7-aw1-shards.png' title='Rune Shard for Sunset Towers'><br>",
    "b_gr7_aw2_shards": "<img src='https://i.ibb.co/473B4zP/b-gr7-aw2-shards.png' title='Rune Shard for Victory Springs'><br>",
    "INS_UNIT_LM_5": "5 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_10": "10 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_15": "15 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LM_25": "25 <br><img src='https://i.ibb.co/jfTTh1Q/barracks-lm.png' title='Light Melee Instant Squad Size'>/<img src='https://i.ibb.co/wCf7xkh/barracks-lm-2.png' title='Light Melee Instant Squad Size'><br>",
    "INS_UNIT_LR_5": "5 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_10": "10 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_15": "10 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_LR_25": "25 <br><img src='https://i.ibb.co/2jH3qG5/barracks-lr.png' title='Light Ranged Instant Squad Size'>/<img src='https://i.ibb.co/M8Wpzb5/barracks-lr-2.png' title='Light Ranged Instant Squad Size'><br>",
    "INS_UNIT_MA_5": "5 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_10": "10 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_15": "10 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_MA_25": "25 <br><img src='https://i.ibb.co/nMz9Zbz/barracks-ma.png' title='Mage Instant Squad Size'>/<img src='https://i.ibb.co/SvgLMw8/barracks-ma-2.png' title='Mage Instant Squad Size'><br>",
    "INS_UNIT_HM_5": "5 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_10": "10 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_15": "10 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HM_25": "25 <br><img src='https://i.ibb.co/1GykVmT/barracks-hm.png' title='Heavy Melee Instant Squad Size'>/<img src='https://i.ibb.co/chCSJVS/barracks-hm-2.png' title='Heavy Melee Instant Squad Size'><br>",
    "INS_UNIT_HR_5": "5 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_10": "10 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_15": "10 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_HR_25": "25 <br><img src='https://i.ibb.co/D9MNhSk/barracks-hr.png' title='Heavy Ranged Instant Squad Size'>/<img src='https://i.ibb.co/KqGV47d/barracks-hr-2.png' title='Heavy Ranged Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_5": "5 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_10": "10 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_15": "10 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LM_25": "25 <br><img src='https://i.ibb.co/85g0RHK/mc-lm-small.png' title='Drone Riders Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_5": "5 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_10": "10 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_15": "10 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_LR_25": "25 <br><img src='https://i.ibb.co/8NRMqzq/mc-lr-small.png' title='Rangers Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_5": "5 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_10": "10 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_15": "10 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_MA_25": "25 <br><img src='https://i.ibb.co/9TKY6Pp/mc-ma-small.png' title='Blossom Mages Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_5": "5 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_10": "10 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_15": "10 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HM_25": "25 <br><img src='https://i.ibb.co/MsCqywh/unit-valorian.png' title='Vallorian Guards Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_5": "5 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_10": "10 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_15": "10 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_MC_HR_25": "25 <br><img src='https://i.ibb.co/c2x0pfJ/unit-frog.png' title='Faineant Frogs Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_5": "5 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_10": "10 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_15": "10 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LM_25": "25 <br><img src='https://i.ibb.co/c3PWGGn/tg-lm-small.png' title='Cerberi Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_5": "5 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_10": "10 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_15": "10 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_LR_25": "25 <br><img src='https://i.ibb.co/80nbSKf/tg-lr-small.png' title='Dryads Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_5": "5 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_10": "10 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_15": "10 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_MA_25": "25 <br><img src='https://i.ibb.co/LNVK6Js/tg-ma-small.png' title='Banshees Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_5": "5 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_10": "10 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_15": "10 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HM_25": "25 <br><img src='https://i.ibb.co/q5ky4WS/unit-orc-warrior.png' title='Orc Warriors Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_5": "5 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_10": "10 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_15": "10 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_UNIT_TG_HR_25": "25 <br><img src='https://i.ibb.co/Gds0422/unit-orc-strategist.png' title='Orc Strategists Instant Squad Size'><br>",
    "INS_REV_SQD_5": "5%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 5%'><br>",
    "INS_REV_SQD_10": "10%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 10%'><br>",
    "INS_REV_SQD_25": "25%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 25%'><br>",
    "INS_REV_SQD_50": "50%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 50%'><br>",
    "INS_REV_SQD_75": "75%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 75%'><br>",
    "INS_REV_SQD_100": "100%<br><img src='https://i.ibb.co/PZCLq1S/vitality-surge-small.png' title='Vitality Surge 100%'><br>",
    "badge_brewery": "<img src='https://i.ibb.co/7RDLWV6/fellowship-adventures-item1.png' title='Dwarven Brewery Badge' style='width: 28px;'><br>",
    "badge_treants": "<img src='https://i.ibb.co/RzhP0kh/fellowship-adventures-item2.png' title='Treant Guild Badge' style='width: 28px;'><br>",
    "badge_bakers": "<img src='https://i.ibb.co/xz01WV7/fellowship-adventures-item3.png' title='Bakers Guild Badge' style='width: 28px;'><br>",
    "badge_carpenters": "<img src='https://i.ibb.co/MMbn5SX/fellowship-adventures-item4.png' title='Carpenters Guild Badge' style='width: 28px;'><br>",
    "luxurious_flacon": "<img src='https://i.ibb.co/0BHjcft/fellowship-adventures-item7.png' title='Luxurious Flacon' style='width: 28px;'><br>",
    "badge_blacksmith": "<img src='https://i.ibb.co/jMndZQw/fellowship-adventures-item6.png' title='Blacksmith Guild Badge' style='width: 28px;'><br>",
    "badge_farmers": "<img src='https://i.ibb.co/xH5ZVx4/fellowship-adventures-item5.png' title='Farmers Guild Badge' style='width: 28px;'><br>",
    "golden_bracelet": "<img src='https://i.ibb.co/FK8XRLW/fellowship-adventures-item8.png' title='Golden Bracelet' style='width: 28px;'><br>",
    "diamond_necklace": "<img src='https://i.ibb.co/bLqZFQc/fellowship-adventures-item9.png' title='Diamond Necklace' style='width: 28px;'><br>",
    "elegant_statue": "<img src='https://i.ibb.co/HrGBhdM/fellowship-adventures-item10.png' title='Elegant Statue' style='width: 28px;'><br>",
    "magic_potion": "<img src='https://i.ibb.co/z8b1T5b/fellowship-adventures-item12.png' title='Magic Potion' style='width: 28px;'><br>",
    "witch_hat": "<img src='https://i.ibb.co/DKK9rdv/fellowship-adventures-item13.png' title='Witch Hat' style='width: 28px;'><br>",
    "badge_wonderhelper": "<img src='https://i.ibb.co/GT4MDYf/fellowship-adventures-item14.png' title='Wonder Society Badge' style='width: 28px;'><br>",
    "money_sack": "<img src='https://i.ibb.co/8B3ZwdF/fellowship-adventures-item16.png' title='Sack of Coins' style='width: 28px;'><br>",
    "elemental_marbles": "<img src='https://i.ibb.co/sgTj589/fellowship-adventures-item20.png' title='Elemental Marbles' style='width: 28px;'><br>",
    "druid_staff": "<img src='https://i.ibb.co/BK9mwsK/fellowship-adventures-item18.png' title='Druid Staff' style='width: 28px;'><br>",
    "ghost_in_a_bottle": "<img src='https://i.ibb.co/d2jXSb7/fellowship-adventures-item17.png' title='Ghost in a bottle' style='width: 28px;'><br>",
    "badge_unit": "<img src='https://i.ibb.co/cL7BsbR/fellowship-adventures-item15.png' title='Elvarian Guard Badge' style='width: 28px;'><br>",
    "arcane_residue": "<img src='https://i.ibb.co/qDXppMz/fellowship-adventures-item19.png' title='Arcane Residue' style='width: 28px;'><br>",
    "enchanted_tiara": "<img src='https://i.ibb.co/Y3xnddG/fellowship-adventures-item21.png' title='Enchanted Tiara' style='width: 28px;'><br>",
    "wand": "<img src='https://i.ibb.co/Kqk0VBJ/fellowship-adventures-item11.png' title='Wand' style='width: 28px;'><br>",
    "b_ch19_aw1_shards": "<img src='https://i.ibb.co/TRBrG90/b-ch19-aw1-shards-small.png' title='Rune Shard for Vallorian Seal Tower'><br>",
    "b_ch19_aw2_shards": "<img src='https://i.ibb.co/sPvTV3X/b-ch19-aw2-shards-small.png' title='Rune Shard for Tree of Enlightenment'><br>",
    "b_ch20_aw1_shards": "<img src='https://i.ibb.co/Yh32gVQ/b-ch20-aw1-shards-small.png' title='Rune Shard for Ancestral Resting Place'><br>",
    "b_ch20_aw2_shards": "<img src='https://i.ibb.co/0cSGf3B/b-ch20-aw2-shards-small.png' title='Rune Shard for Scouts Tavern'><br>",
    "spire_diplomacy_joker": "<img src='https://i.ibb.co/Fgkb1HS/spire-diplomacy-joker.png' title='Spectral Stone'><br>",
}

var chapter_icons = {
    1: "https://i.ibb.co/kQF5s0q/ch1.png title='Chapter 1'",
    2: "https://i.ibb.co/DfkmS1H/ch2.png title='Chapter 2'",
    3: "https://i.ibb.co/mFkxVRb/ch3.png title='Chapter 3'",
    4: "https://i.ibb.co/TcDB1Vx/ch4.png title='Chapter 4'",
    5: "https://i.ibb.co/F61wRpp/ch5.png title='Chapter 5'",
    6: "https://i.ibb.co/qYDnBNk/ch6.png title='Dwarves'",
    7: "https://i.ibb.co/7yHBTJV/ch7.png title='Fairies'",
    8: "https://i.ibb.co/sWcQSrp/ch8.png title='Orcs and Goblins'",
    9: "https://i.ibb.co/tsm2HCs/ch9.png title='Woodelves'",
    10: "https://i.ibb.co/sqkZ7FN/ch10.png title='Sorcerers and Dragons'",
    11: "https://i.ibb.co/D4sgMFf/ch11.png title='Halflings'",
    12: "https://i.ibb.co/KVrY4M2/ch12.png title='Elementals'",
    13: "https://i.ibb.co/Sx7bcfG/ch13.png title='Amuni'",
    14: "https://i.ibb.co/5h3nr8K/ch14.png title='Constructs'",
    15: "https://i.ibb.co/mbhNzvt/ch15.png title='Elvenar'",
    16: "https://i.ibb.co/qjFYznn/ch16.png title='Embassies'",
    17: "https://i.ibb.co/W5CtfR2/ch17.png title='Traders of Unur'",
    18: "https://i.ibb.co/ZxGJSVv/ch18.png title='Team Spirit'",
    19: "https://i.ibb.co/Y4gW0Vy/ch19.png title='Revenge of the Exile'",
    20: "https://i.ibb.co/Vv6rC8r/ch20.png title='The Power of Music'",
}

var grIds = {
    "dwarves": "ch6",
    "fairies": "ch7",
    "orcs": "ch8",
    "woodelves": "ch9",
    "sorcerers": "ch10",
    "halflings": "ch11",
    "elementals": "ch12",
    "amuni": "ch13",
    "constructs": "ch14",
    "elvenar": "ch15",
    "embassies": "ch16",
    "tradersofunur": "ch17",
    "teamspirit": "ch18",
    "revengeofexile": "ch19",
    "powerofmusic": "ch20",
}

var navbarNew = {
    "active": true,
    "img": {
        "src": "https://i.ibb.co/n0KBPgt/new-sign.png",
        "style": "width: 50px;",
    }
}

var moreNavbarContent = [
    // FELLOWSHIP ADVENTURES
    {   
        "className":    "dropdown-item text-dark", 
        "href":         "fellowship-adventures.html", 
        "id":           "navitem_fellowship_adventures", 
        "innerHTML":    `Fellowship Adventures`,
        "img":          {
            "src":      "https://i.ibb.co/8mQV9TJ/fellowship-adventures-waypoint.png",
            "style":    "width: 24px; margin-right: 6px; margin-bottom: 4px;",
        }
    },
    // SEASONS
    {
        "className":    "dropdown-item text-dark",
        "href":         "seasons.html",
        "id":           "navitem_seasons",
        "innerHTML":    "Seasons",
        "img": {
            "src":      "https://i.ibb.co/87MNrBB/season-pass.png",
            "style":    "width: 25px; margin-right: 6px; margin-bottom: 1px; margin-left: 0px;",
        }
    },
    /*{
        "className":    "dropdown-item text-dark",
        "href":         "tournaments.html",
        "id":           "navitem_tournaments",
        "innerHTML":    "Tournaments",
        "img": {
            "src":      "https://i.ibb.co/k42MQs2/tournament-icon.png",
            "style":    "width: 25px; margin-right: 5px; margin-bottom: 4px; margin-left: 0px;",
        }
    },*/
    // ---------------
    // CONTACT
    {   
        "className":    "dropdown-item text-dark", 
        "href":         "contact.html", 
        "id":           "navitem_contact", 
        "innerHTML":    `Contact`
    },
    // ABOUT ME
    {   
        "className":    "dropdown-item text-dark", 
        "href":         "about-me.html", 
        "id":           "navitem_about_me", 
        "innerHTML":    `About Me`
    },
    // DONATE
    {   
        "className":    "dropdown-item text-dark", 
        "href":         "donate-create.html", 
        "id":           "navitem_donate", 
        "innerHTML":    `Donate`
    },
]
